### ISSUE TITLE
Ruby installation issues

### ISSUE THREAD

**Issue by NicoWde** [vitobotta/hetzner-k3s#1]
Hey Vito,

thanks for this amazing project! :) 
I wanted to try a little bit around, but with Ubuntu 20.04 and standard-repo Ruby I get issues, that some packages are to new. Before I start digging into this, since I have exactly 0 Ruby knowledge, I'd like to hear at least someting about your Ruby runtime.

I'd be happy to enhance Readme afterwards :)

Kind Regards,
Nico

**Comment by thelittlebug** [comment]
i also have a ubuntu 20.04. never installed ruby before. what worked for me:
```
sudo apt install ruby ruby-dev
sudo gem install hetzner-k3s
```

i have no experience with ruby. but i was unable to install the gem without sudo. maybe theres a flag to install gems in a "usermode"?

**Comment by NicoWde** [comment]
Ahh... I see my issue now.. missing build-essential

so worked now with:
```
sudo apt install ruby ruby-dev build-essential
sudo gem install hetzner-k3s
```

Thank you very much @thelittlebug!

**Comment by vitobotta** [comment]
Glad you got it working! I am planning to create some ready binaries that you just download without having to install the Ruby runtime separately. I need to see which tool to use for this.
