### ISSUE TITLE
overwriting  ~/.kube/config data

### ISSUE THREAD

**Issue by qari** [vitobotta/hetzner-k3s#107]
I have some clusters/context in my config file ~/.kube/config. But after create new cluster by hetzner-k3s all my config changed only with new data of new cluster. How can I create new cluster with add new data like new context, not cleaning previous data of clusters.

**Comment by vitobotta** [comment]
Hi, that should not happen. The tool writes the kubeconfig to the file you specify in the config file. Did you set it to ~/.kube/config? I recommend to specify another file, maybe in the same locations as the config file, and then manually copy it to whereever you want.

**Comment by qari** [comment]
Yes, I have set `kubeconfig_path: "~/.kube/config"` and every time after create new cluster all data were replace for new one. So, I think change config path and add data manually to  config file that no bad way :)
