### ISSUE TITLE
post_create_commands and additional_packages

### ISSUE THREAD

**Issue by maxclax** [vitobotta/hetzner-k3s#109]
So, I have added to my config file code bellow. But I see also ability add some packages with `additional_packages`. How that works in different OS? and what about lifecycle? As I understand post_create_commands will be last one for running? If I want to update or add extra nodes will be additional_packages and post_create_commands run for active nodes? 

and how I can labeled nodes in setup way? Does it works https://github.com/vitobotta/hetzner-k3s/issues/98 ?

```
post_create_commands:
- apt update && apt upgrade -y
# Fix for K3s on Debian (Pods can't be scheduled)
- apt -y install apparmor apparmor-utils
#
- apt -y install mc htop vim wget git zsh podman iftop atop lsof fail2ban jq make
#
- apt -y install tmux tmuxinator
- git clone https://github.com/gpakosz/.tmux.git /root/.tmux ; ln -s -f /root/.tmux/.tmux.conf /root/ ; cp /root/.tmux/.tmux.conf.local /root/
#
- sh -c "$(wget https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)" -y
- sed -i 's/\/bin\/bash/\/usr\/bin\/zsh/g' /etc/passwd
- /usr/bin/git clone https://github.com/zsh-users/zsh-autosuggestions /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
- sed -i 's/plugins=(git)/plugins=(zsh-autosuggestions git docker docker-compose poetry kubectl)/g' /root/.zshrc
#
- apt autoremove -y
- shutdown -r now
```

**Comment by maxclax** [comment]
and can I labeled nodes in setup way?

**Comment by vitobotta** [comment]
Hi, 

- installing packages you specify happens only once the nodes are first created. If you want to upgrade them or install something else after the fact, you need to SSH into the nodes and do it manually.
- The machines are provided by default with Ubuntu unless you specify another image, so the packages and the commands you specify should match that
- If you add new nodes to an existing cluster, it will run the post commands and install the additional packages on them as expected
- the node labelling was introduced in v0.6.2 IIRC but I recommend you use the gem because there are some issues with the binaries. I am currently rewriting the tool in Crystal to be able to offer proper binaries and solve some other issues I have with the Ruby version. If you have problems with 0.6.2 I recommend you stick to a release from before I introduced this changes, 0.5.9 and label the nodes manually for now.

**Comment by maxclax** [comment]
`the node labelling was introduced in v0.6.2 IIRC but I recommend you use the gem because there are some issues with the binaries. I am currently rewriting the tool in Crystal to be able to offer proper binaries and solve some other issues I have with the Ruby version. If you have problems with 0.6.2 I recommend you stick to a release from before I introduced this changes, 0.5.9 and label the nodes manually for now.` on debian 10-11 and centos 8-9 I don't have any proplem with the binaries.

**Comment by vitobotta** [comment]
@maxclax Nice to hear that you haven't had any problems with the binaries, other people have. Ruby isn't really great for this since it's not compiled, that's why I am rewriting it in Crystal.

**Comment by rmelilloii** [comment]
Hello, good afternoon and happy Friday! @vitobotta , quick one related to this subject. When I try to create a muilti-line file from "post_create_commands" it fails. My one-liner:
`echo -e "apiVersion: audit.k8s.io/v1\nkind: Policy\nrules:\n- level: Request\n  resources:\n  - group: \"\"\n    resources: [\"pods\", \"services\", \"configmaps\", \"secrets\", \"deployments\", \"statefulsets\", \"ingresses\", \"jobs\", \"cronjobs\"]\n- level: RequestResponse\n  user: \"\"\n  verbs: [\"exec\", \"attach\", \"port-forward\", \"create\", \"apply\", \"delete\", \"edit\", \"proxy\", \"run\", \"scale\", \"expose\", \"rollou\", \"config\", \"label\", \"annotate\"]" > /var/lib/rancher/k3s/server/audit.yaml`

Should such command be accepted or better to download/create the file using cURL?

Cheers.

**Comment by vitobotta** [comment]
@rmelilloii can you show the config yaml? it depends on how you write the yaml

**Comment by rmelilloii** [comment]
> @rmelilloii can you show the config yaml? it depends on how you write the yaml

Sure can. Line 31. Now that you say that, maybe I need to double scape the double quotes?
`---
hetzner_token: *****
cluster_name: romulo-k3saudit-01
kubeconfig_path: "./kubeconfig"
k3s_version: v1.25.9+k3s1
public_ssh_key_path: "~/.ssh/id_rmii.pub"
private_ssh_key_path: "~/.ssh/id_rmii"
use_ssh_agent: false # set to true if your key has a passphrase or if SSH connections don't work or seem to hang without agent. See https://github.com/vitobotta/hetzner-k3s#limitations
# ssh_port: 22
ssh_allowed_networks:
  - 0.0.0.0/0 # ensure your current IP is included in the range
api_allowed_networks:
  - 0.0.0.0/0 # ensure your current IP is included in the range
private_network_subnet: 10.0.0.0/16 # ensure this doesn't overlap with other networks in the same project
disable_flannel: false # set to true if you want to install a different CNI
schedule_workloads_on_masters: true
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.18.0/ccm-networks.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.5.1/deploy/kubernetes/hcloud-csi.yml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
masters_pool:
  instance_type: cx41
  instance_count: 1
  location: nbg1
  image: ubuntu-22.04
post_create_commands:
- echo fs.inotify.max_user_watches=1048576|tee -a /etc/sysctl.conf
- echo fs.inotify.max_user_instances=1024|tee -a /etc/sysctl.conf
- sed -i "/2a01:4ff:ff00::add:2/d" /etc/netplan/50-cloud-init.yaml
- netplan apply
- mkdir -p -m 700 /var/lib/rancher/k3s/server/logs
- echo -e "apiVersion: audit.k8s.io/v1\nkind: Policy\nrules:\n- level: Request\n  resources:\n  - group: \"\"\n    resources: [\"pods\", \"services\", \"configmaps\", \"secrets\", \"deployments\", \"statefulsets\", \"ingresses\", \"jobs\", \"cronjobs\"]\n- level: RequestResponse\n  user: \"\"\n  verbs: [\"exec\", \"attach\", \"port-forward\", \"create\", \"apply\", \"delete\", \"edit\", \"proxy\", \"run\", \"scale\", \"expose\", \"rollou\", \"config\", \"label\", \"annotate\"]" > /var/lib/rancher/k3s/server/audit.yaml
- echo Ciphers aes256-ctr,aes192-ctr,aes128-ctr|tee -a /etc/ssh/sshd_config
- echo MACs hmac-sha2-256,hmac-sha2-512|tee -a /etc/ssh/sshd_config
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
enable_encryption: true
kube_api_server_args:
- audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log
- audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml
- audit-log-maxage=30
- audit-log-maxbackup=11
- audit-log-maxsize=100`

**Comment by vitobotta** [comment]
Please use code snippets next time otherwise the code is not easy to ready :)

Try this syntax to create that file:

```yaml
post_create_commands:
- |
  cat > /var/lib/rancher/k3s/server/audit.yaml <<EOF
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
  - level: Request
    resources:
    - group: ""
      resources: ["pods", "services", "configmaps", "secrets", "deployments", "statefulsets", "ingresses", "jobs", "cronjobs"]
  - level: RequestResponse
    user: ""
    verbs: ["exec", "attach", "port-forward", "create", "apply", "delete", "edit", "proxy", "run", "scale", "expose", "rollou", "config", "label", "annotate"]
  EOF

**Comment by rmelilloii** [comment]
Hello @vitobotta thanks and sorry for that.
The deploy accepts the yaml as valid, but it stops at:
![image](https://github.com/vitobotta/hetzner-k3s/assets/28736500/818c1d19-88f2-441c-b1f8-70dbd681175a)

to show the indentation:
![image](https://github.com/vitobotta/hetzner-k3s/assets/28736500/fd0f9280-cb5a-4b15-98c3-ea146513f83c)

`
post_create_commands:
- echo fs.inotify.max_user_watches=1048576|tee -a /etc/sysctl.conf
- echo fs.inotify.max_user_instances=1024|tee -a /etc/sysctl.conf
- sed -i "/2a01:4ff:ff00::add:2/d" /etc/netplan/50-cloud-init.yaml
- netplan apply
- mkdir -p -m 700 /var/lib/rancher/k3s/server/logs
- |
  cat <<EOF > /var/lib/rancher/k3s/server/audit.yaml
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
  - level: Request
    resoureces:
    - group: ""
      resources: ["pods", "services", "configmaps", "secrets", "deployments", "statefulsets", "ingresses", "jobs", "cronjobs"]
  - level: RequestResponse
    user: ""
    verbs: ["exec", "attach", "port-forward", "create", "apply", "delete", "edit", "proxy", "run", "scale", "expose", "rollout", "config", "label", "annotate"]
  EOF
- echo Ciphers aes256-ctr,aes192-ctr,aes128-ctr|tee -a /etc/ssh/sshd_config
- echo MACs hmac-sha2-256,hmac-sha2-512|tee -a /etc/ssh/sshd_config
- apt update
- apt upgrade -y
- apt autoremove -y
- shutdown -r now
`

**Comment by vitobotta** [comment]
Can you try with `|-` instead of just `|`?

**Comment by rmelilloii** [comment]
Yes, the issue is the same, it hangs/does nothing.
And also fails with a "simpler file content".
Example:
```
- |-
  cat <<EOF > /var/lib/rancher/k3s/server/audit.yaml
  blablabla
  EOF
```

```
- |
  cat <<EOF > /var/lib/rancher/k3s/server/audit.yaml
  blablabla
  EOF
```

**Comment by vitobotta** [comment]
If you remove that section altogether, does it still hang? I mean are you sure it hangs because of that multiline command?

**Comment by vitobotta** [comment]
It may be because the directory where you are creating the file doesn't exist yet at that stage. Try adding another command before that to create the directory

**Comment by rmelilloii** [comment]
The error is the same when saving the file to "~/file.yaml"... But yes, I tried creating it and the error is the same.

**Comment by vitobotta** [comment]
Not sure what could be the reason. I am also sick at the moment so I can't really test it myself right now.

**Comment by rmelilloii** [comment]
No worries and thanks anyway. I will "pause" this effort for now, and proceed with related steps after cluster deployment.
Keep an eye to see if someone else has a similar need.
Cheers, take care.
