### ISSUE TITLE
Feature request: Rancher as container management solution

### ISSUE THREAD

**Issue by Agilitytime** [vitobotta/hetzner-k3s#11]
Is it possible to optionally deploy Rancher as a container management solution ? 
it would be perfect if this was an all in one solution.

Thanks for your effort and work!!!

**Comment by vitobotta** [comment]
I can see if I add an option.

**Comment by vitobotta** [comment]
Hi, I was looking into it but decided to leave it for now because it's outside of the scope of the tool. May reconsider later, not sure. Rancher is pretty easy to install with Helm anyway.
