### ISSUE TITLE
schedule_workloads_on_masters

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#111]
Hi,

i switched the `schedule_workloads_on_masters` setting to `false`, but the ingress loadbalancer still points/checking the master nodes too. Is this the normal working? Is there any way to ignore the master nodes from LB targets?

**Comment by vitobotta** [comment]
Hi, if the pods linked to the load balancer are still running on masters then it's normal. If you restart the deployment so that all pods are rescheduled on worker nodes only, the load balancer should be updated automatically.

**Comment by dyipon** [comment]
thanks!
