### ISSUE TITLE
one node always can't load images

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#112]
I tried to install several various clustert, but always have one node which can't load docker images:
![Screenshot from 2022-12-04 21-17-03](https://user-images.githubusercontent.com/35313394/205514374-2b5c99ca-3a8f-4121-9fd1-e58741c24610.png)
![Screenshot from 2022-12-04 21-08-54](https://user-images.githubusercontent.com/35313394/205514387-4f3eebc9-bfdf-406c-8a16-3cf2a272c06d.png)
![Screenshot from 2022-12-04 21-01-10](https://user-images.githubusercontent.com/35313394/205514406-99cfa645-3058-44b8-b6f4-9d6247d34b2f.png)

the faulty node gives this error:
![Screenshot from 2022-12-04 21-09-09](https://user-images.githubusercontent.com/35313394/205514433-0d3e8ffc-2dc4-4317-a157-9163fcd60457.png)

I dont' know why it happens, anybody have an idea what can cause this issue?

**Comment by vitobotta** [comment]
Does it happen again if you delete the pod and let it be rescheduled?

**Comment by dyipon** [comment]
yes, tried, did not help. 
i tried to ssh into the node, and manually download the image via `k3s crictl pull image`... but got the same error.

**Comment by vitobotta** [comment]
Weird. Not sure what could be the problem. I think I came across something similar a while ago but usually rescheduling the pods helped. Which version of k3s are you using?

**Comment by vitobotta** [comment]
Wait the error message shows a 403 status code when trying to pull the image, so perhaps there is some temporary issue with that registry. Does it happen to other pods if you delete them and let them be rescheduled?

**Comment by dyipon** [comment]
I've tried various 1.24.x and 1.25.x versions, got the same error.
And I've tried repull the same image from other node, and its working, so registry is working fine.
```
root@hetzner-k3s-cx11-pool-intel-worker2:~# k3s crictl pull k8s.gcr.io/sig-storage/livenessprobe:v2.1.0
E1204 21:04:30.919709    4546 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/sig-storage/livenessprobe:v2.1.0\": failed to resolve reference \"k8s.gcr.io/sig-storage/livenessprobe:v2.1.0\": pulling from host k8s.gcr.io failed with status code [manifests v2.1.0]: 403 Forbidden" image="k8s.gcr.io/sig-storage/livenessprobe:v2.1.0"
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image "k8s.gcr.io/sig-storage/livenessprobe:v2.1.0": failed to resolve reference "k8s.gcr.io/sig-storage/livenessprobe:v2.1.0": pulling from host k8s.gcr.io failed with status code [manifests v2.1.0]: 403 Forbidden 
```
other node:
```
root@hetzner-k3s-cx11-pool-intel-worker3:~# k3s crictl pull k8s.gcr.io/sig-storage/livenessprobe:v2.1.0
Image is up to date for sha256:de977053da40618925fe026117ee9988eb06a1c5586c3db258e4e5d17d5351a0

```
anyway it's working with other registries, maybe k8s.gcr.io just banned the node.
Thanks for your help @vitobotta!

**Comment by vitobotta** [comment]
You can try draining and then deleting the node, and re-running my tool to recreate it. Why would they ban the node?

**Comment by vitobotta** [comment]
Have you seen this? It looks like they migrated registry https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/

**Comment by dyipon** [comment]
Well, I drained, deleted and recreated, but I get the same issue, so I think its because the node's IP (the new VM got the same IP as previously).

I added a new extra node to the cluster, and it can pull the images without any issue.

I just read through the link you've mentioned, but k3s releases (v1.25) still pointing to the old address, despite:
_Starting with Kubernetes 1.25, our container image registry has changed from k8s.gcr.io to [registry.k8s.io](https://registry.k8s.io/)._
I hope it will be fixed in future releases
