### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#115]
Hi,

happy new year :)

I tried to install via homebrew, but got the next error:
```
$ brew install vitobotta/tap/hetzner_k3s
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:282:in `determine_active_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:213:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:308:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:308:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:469:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:634:in `block in formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:630:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:630:in `formulae'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:147:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:97:in `<main>'

```

After it, I tried to manually setup the [latest binary](https://github.com/vitobotta/hetzner-k3s/releases/download/v0.6.5/hetzner-k3s-linux-x86_64) but got another error:
```
$ ./hetzner-k3s-linux-x86_64
./hetzner-k3s-linux-x86_64: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
but Im sure latest libssl-dev is installed:
```
libssl-dev is already the newest version (1.1.1n-0+deb11u3).
libevent-dev is already the newest version (2.1.12-stable-1).
libssh2-1-dev is already the newest version (1.9.0-2).
```

What's is the correct way to install via brew?
And what debian packages needed to use the binary packages?

Thanks

**Comment by vitobotta** [comment]
Oops, I had forgotten that Homebrew also exists for Linux. The binaries you can install with brew are Mac only at the moment, will update this to include Linux. So for now you need to download the binary.

Weird though, I didn't need to install anything else at least on Ubuntu. You are on Debian I guess?

**Comment by dyipon** [comment]
yes, debian bullseye with those packages:
```
dpkg -l | grep ssl
ii  libevent-openssl-2.1-7:amd64      2.1.12-stable-1                amd64        Asynchronous event notification library (openssl)
ii  libssl-dev:amd64                  1.1.1n-0+deb11u3               amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.1:amd64                   1.1.1n-0+deb11u3               amd64        Secure Sockets Layer toolkit - shared libraries
ii  libzstd1:amd64                    1.4.8+dfsg-2.1                 amd64        fast lossless compression algorithm

```

**Comment by vitobotta** [comment]
Which libssl.so.* files do you have in your system?

**Comment by dyipon** [comment]
```
locate libssl.so | grep usr | grep -v docker
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.1

```

**Comment by vitobotta** [comment]
I'll test with DEbian Bullseye VM so I can investigate the issue more easily. In the future I will try and compile to a static binary so that you don't need to install these dependencies anymore.

**Comment by dyipon** [comment]
thanks!

**Comment by vitobotta** [comment]
Are you using Bullseye server or desktop?

**Comment by dyipon** [comment]
Im using debian server (its a virtualized machine). Tomorrow I will try to complite openssl 3

**Comment by vitobotta** [comment]
OK, thx. Will update as soon as I have news. I am gonna try now

**Comment by vitobotta** [comment]
Hi, I managed to create a statically compiled binary, so you should no longer need to install dependencies. It works for me. Can you please try the v0.6.6 binary? Thanks

**Comment by Privatecoder** [comment]
@vitobotta is it expected that it is required to install `libevent` and `bdw-gc` as dependencies via homebrew to get v0.6.7 running (at least on Monterey)?

**Comment by vitobotta** [comment]
> @vitobotta is it expected that it is required to install `libevent` and `bdw-gc` as dependencies via homebrew to get v0.6.7 running (at least on Monterey)?

I didn't need to on my two Macs. Only libssh2. Looks like I forgot to add it to the README, will do it now.

**Comment by Privatecoder** [comment]
Tried to run it, got an error for both:

```
dyld[93244]: Library not loaded: '/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib'
  Referenced from: '/opt/homebrew/Cellar/hetzner_k3s/0.6.7/bin/hetzner-k3s'
  Reason: tried: '/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib' (no such file), '/usr/local/lib/libgc.1.dylib' (no such file), '/usr/lib/libgc.1.dylib' (no such file)
```

and

```
dyld[93206]: Library not loaded: '/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib'
  Referenced from: '/opt/homebrew/Cellar/hetzner_k3s/0.6.7/bin/hetzner-k3s'
  Reason: tried: '/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib' (no such file), '/usr/local/lib/libgc.1.dylib' (no such file), '/usr/lib/libgc.1.dylib' (no such file)
```

**Comment by vitobotta** [comment]
> Tried to run it, got an error for both:
> 
> 
> 
> ```
> 
> dyld[93244]: Library not loaded: '/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib'
> 
>   Referenced from: '/opt/homebrew/Cellar/hetzner_k3s/0.6.7/bin/hetzner-k3s'
> 
>   Reason: tried: '/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib' (no such file), '/usr/local/lib/libgc.1.dylib' (no such file), '/usr/lib/libgc.1.dylib' (no such file)
> 
> ```
> 
> 
> 
> and
> 
> 
> 
> ```
> 
> dyld[93679]: Library not loaded: '/opt/homebrew/opt/libevent/lib/libevent-2.1.7.dylib'
> 
>   Referenced from: '/opt/homebrew/Cellar/hetzner_k3s/0.6.7/bin/hetzner-k3s'
> 
>   Reason: tried: '/opt/homebrew/opt/libevent/lib/libevent-2.1.7.dylib' (no such file), '/usr/local/lib/libevent-2.1.7.dylib' (no such file), '/usr/lib/libevent-2.1.7.dylib' (no such file)
> 
> ```

Probably I have some dependencies already installed. Can you try installing glibc? I need to set up macOS from scratch in a VM to test this

**Comment by Privatecoder** [comment]
> Probably I have some dependencies already installed. Can you try installing glibc? I need to set up macOS from scratch in a VM to test this

I installed `libevent` and `bdw-gc` via `brew install` which fixes it and the tool runs fine (had to change the cli-syntax and update my cluster-config though.. ;)

Do you still want me to install `glibc` (to test what exactly)?

**Comment by vitobotta** [comment]
> > Probably I have some dependencies already installed. Can you try installing glibc? I need to set up macOS from scratch in a VM to test this
> 
> 
> 
> I installed `libevent` and `bdw-gc` via `brew install` which fixes it and the tool runs fine (had to change the cli-syntax and update my cluster-config though.. ;)
> 
> 
> 
> I.e: I was just asking to see if we need to add this to the Readme **OR** if you plan to solve these dependencies differently.
> 
> 
> 
> Do you still want me to install `glibc` (to test what exactly)?

Awesome, I will update the README with your finding, thanks!

**Comment by dyipon** [comment]
Tested, and its working, thanks for fast response!
