### ISSUE TITLE
Hetzner `us-west` not supported

### ISSUE THREAD

**Issue by XMGamingMaster** [vitobotta/hetzner-k3s#116]
The new `us-west` region is currently not supported because of this line: https://github.com/vitobotta/hetzner-k3s/blob/817ea93364134964c20268f604e4642a04f8eabf/src/hetzner/network/create.cr#L42

I think it would be easier to get the network zone from the hetzner locations api.

**Comment by vitobotta** [comment]
Thanks for reporting this! I will fix it soon. For the time being as a quick fix I will add the location to that condition. Later I will query the API

**Comment by vitobotta** [comment]
Hi, I've released v0.6.7 which addresses this. Please give it a try and lemme know.

**Comment by XMGamingMaster** [comment]
Hi, `us-west` works now. Thanks!
