### ISSUE TITLE
SSH allowed network

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#118]
Hello,

i have 2 IP ranges defined in ssh_allowed_networks:
```
ssh_allowed_networks:
  - 1.2.3.4/32
  - 10.1.0.0/16
```

when I start the app, i get the next notification:
```
Some information in the configuration file requires your attention:
  - Your current IP 1.2.3.4 does not belong to the SSH allowed network 94.125.179.0/24
```

Previous version did not have any problem with that.
I don't know what can cause this log, maybe the /32?

**Comment by vitobotta** [comment]
The cidr mismatch between the portion of the config and the network in the error message is confusing. /32 means a single IP so that notation as it is would only allow the exact IP 1.2.3.4 and nothing else. But in the error message you have 94.125.179.0/24, so I assume that's the actual network you have in the config? Please clarify the config :)

**Comment by dyipon** [comment]
thats my current config, but i did not want to expose my ip ranges:
```
ssh_allowed_networks:                                                                                                                                                    
  - 88.151.99.52                                                                                                                                                         
  - 94.125.179.0/24    
```
error message:
`- Your current IP 88.151.99.52 does not belong to the SSH allowed network 94.125.179.0/24`

With previous version it's worked.

**Comment by vitobotta** [comment]
Let me check and I will get back to you soon.

**Comment by vitobotta** [comment]
I found the issue, it happens when you specify multiple networks. Will release a fix soon.

**Comment by dyipon** [comment]
thanks. Could you delete this issue permanently? Unfortunately I commented my production keys, i did not want to expose :/

**Comment by vitobotta** [comment]
Can you please try version 0.6.9? This should fix the problem with the network validation. Will delete the issue.
