### ISSUE TITLE
[Request] Do not save `k3s-releases.yaml` in same dir

### ISSUE THREAD

**Issue by Niek** [vitobotta/hetzner-k3s#122]
Maybe it's my OCD, but I don't like the `k3s-releases.yaml` being created every time I run `hetzner-k3s create` in the cwd. Would it be possible to store this file `$TMPDIR` instead? Or it it supposed to be e.g. checked in?

**Comment by vitobotta** [comment]
The file gets created only once  to cache the list of releases, because Github's API has a rate limit which is easily hit. I can change the file to a temporary path though.

**Comment by vitobotta** [comment]
Done in v0.7.0. I guess we can close? :)

**Comment by Niek** [comment]
This is the most ridiculous turnaround time for a fix I have ever seen 😄  You're amazing @vitobotta - thanks!

**Comment by vitobotta** [comment]
> This is the most ridiculous turnaround time for a fix I have ever seen 😄 You're amazing @vitobotta - thanks!

Thank you for the suggestion!
