### ISSUE TITLE
Cluster create not woking - for my setup :(

### ISSUE THREAD

**Issue by promofu** [vitobotta/hetzner-k3s#123]
Hi Vito,

just started playing with your awesome hetzner-k3s tooling. Unfortunately it doesn't seem
to work for me for neither 0.7.0, nor 0.6.9 nor 0.6.7. I am on a Ubuntu 22.04 LTS Linux
System.

The creation seems to get stuck in timeouts when I am trying to create a "sandbox" cluster from scratch.

My sandbox.yaml is almost identical to the sample you provide in the ReadMe except for
the hetzner_token and the SSH key parts... and I did some minor adjustments to
master instance_count and the workers locations. Also I commented out the "big"
workers section.

Here is the logs of "hetzner-k3s create --config sandbox.yaml":

```
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating network...done.
Creating firewall...done.
SSH key already exists, skipping.
Creating placement group sandbox-masters...done.
Creating placement group sandbox-small...done.
Creating server sandbox-cpx21-pool-small-worker1...
Creating server sandbox-cpx21-pool-small-worker2...
Creating server sandbox-cpx21-master1...
...server sandbox-cpx21-pool-small-worker2 created.
...server sandbox-cpx21-pool-small-worker1 created.
...server sandbox-cpx21-master1 created.
Waiting for server sandbox-cpx21-pool-small-worker2 to be ready...
Waiting for server sandbox-cpx21-pool-small-worker1 to be ready...
Waiting for server sandbox-cpx21-master1 to be ready...
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
Unhandled exception in spawn: timeout after 00:00:05 (Tasker::Timeout)
  from /usr/share/crystal/src/array.cr:114:31 in 'execute!'
  from /workspace/lib/tasker/src/tasker.cr:29:7 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```

I remember the part on "idempotency" of your tooling so I CTRL-Ced and retried the create but to no avail.

From the Hetzner Cloud Console I can confim that all three servers are being created and are accessible using
SSH - I do not see any activity on either of them (looking at HTOP for example).

Any hints on how to further track that one down ?

**Comment by promofu** [comment]
From the Cloud Console I can also confirm that besides the three Servers there is a network and a set of firewall rules created and applied.

**Comment by vitobotta** [comment]
Hi! Are you using an SSH key with a passphrase? If yes that's not supported because it would be requested too many times during the cluster creation. I need to update the README about it.

**Comment by promofu** [comment]
🤦🏻‍♂️ ... yeah the obvious but it would help to have it in the ReadMe as a sidenote ;-)

Works like a charm now - thanks a ton !

**Comment by vitobotta** [comment]
No prob :)

**Comment by vitobotta** [comment]
@promofu Hi, FYI v1.0.2 allows using an SSH agent (by setting `use_ssh_agent` to `true`) which among other things makes it possible to use keys with a passphrase :)

**Comment by promofu** [comment]
@vitobotta your pace is incredible... can barely cope ;-)

**Comment by vitobotta** [comment]
> @vitobotta your pace is incredible... can barely cope ;-)

Thanks for the kind words!
