### ISSUE TITLE
api_allowed_networks:

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#124]
Hi,

im trying to protect kubernetes API with this configuration:
```
api_allowed_networks:
  - 1.2.3.4
  - 5.6.7.0/24
```
But after cluster deployed, I can still reach the API from a non-whitelisted IP:
```
telnet 167.235.109.140 6443
Trying 167.235.109.140...
Connected to 167.235.109.140.
Escape character is '^]'.
quit
```

Am I trying the correct way, or what can cause that issue?

**Comment by vitobotta** [comment]
Hi, is this with a multimaster -HA configuration? If yes, this won't for for now because Hetzner Cloud doesn't support firewalls in load balancers yet, and a load balancer is created automatically for the API if there are more than one master. Can you confirm that this is your case?

**Comment by dyipon** [comment]
Yes, its multimaster HA. Thanks for fast response!

**Comment by vitobotta** [comment]
Np. Unfortunately there is nothing I can do about this until Hetzner adds firewall support to load balancers. :)
