### ISSUE TITLE
Feat: Add ability to choose the image, mainly between Ubuntu and Rocky

### ISSUE THREAD

**Issue by aleksasiriski** [vitobotta/hetzner-k3s#126]
Add ability to choose the image, mainly between Ubuntu and Rocky

**Comment by vitobotta** [comment]
You can already set the image (even a custom one), see README for details.

**Comment by aleksasiriski** [comment]
Sorry, didn't see that part of the README

**Comment by vitobotta** [comment]
No prob :)

**Comment by aleksasiriski** [comment]
Sadly when I set the image to `rocky-9` or `ubuntu-22.04` the script hangs waiting for the servers to come online. I didn't have the time to debug this so I just went with the default `ubuntu-20.04`

**Comment by vitobotta** [comment]
I haven't tested with other images to be honest. Why would you prefer Rocky?

**Comment by aleksasiriski** [comment]
I don't mean to be rude but I am extremely biased when it comes to Ubuntu, I know it's the standard in cloud currently but whenever I can I prefer to use RHEL/RHEL based or pure Debian. It's not much in the functionality than a personal preference not to use Canonical's products.

I'm okay using Ubuntu for my cluster with your script right now since everything I do is via kubectl so I never have to even see that my servers are running Ubuntu, honestly it would be amazing if Hetzner added [K3OS](https://k3os.io/) as an option, or [Talos](https://www.talos.dev/)..

**Comment by aleksasiriski** [comment]
Yes, I just added the config option `image: rocky-9` and when that didn't work i tried `image: ubuntu-22.04`.

Both of those are available as instant deploy images on Hetzner.

**Comment by vitobotta** [comment]
Thanks for confirming. Like I mentioned on Reddit I fixed the issue preventing clusters from creating with other OS, so this works now. I need to fix an issue with the cluster autoscaler (which crashes with Rocky Linux) and then will make a new release.
