### ISSUE TITLE
SSH fails silently during machine status check

### ISSUE THREAD

**Issue by madisp** [vitobotta/hetzner-k3s#129]
With the new Crystal version for some reason creating a cluster is stuck forever. I rebuilt the project locally with some extra logging and it seems to be stuck in a `SSH2::SessionError: 'ERR -19: Callback returned error'` loop.

If I load the priv key into an agent and do `session.login_with_agent("root")` instead of priv+pub key in `ssh.cr` then `hetzner-k3s` succeeds.

**Comment by vitobotta** [comment]
Hi, do you use a key with passphrase?

**Comment by vitobotta** [comment]
Hi, I released v1.0.2 that allows you to use an SSH agent by setting `use_ssh_agent` to `true`. Do you mind checking if this solves the problem with your key? Thanks

**Comment by madisp** [comment]
> Hi, I released v1.0.2 that allows you to use an SSH agent by setting `use_ssh_agent` to `true`. Do you mind checking if this solves the problem with your key? Thanks

you're right, I did use a passphrase! I guess the Ruby version fell back to agent automatically, `use_ssh_agent: true` fixed this for me, thanks!

**Comment by vitobotta** [comment]
Awesome, thanks for confirming!
