### ISSUE TITLE
Timeout when trying to create +9 servers at once

### ISSUE THREAD

**Issue by pucilpet** [vitobotta/hetzner-k3s#14]
Hi!
I found that when I tried to create 9 servers as per your example, I will always get only 8 servers created and the script timeouts when the 9th "waiting for server to be up" (also the script exits before completion).

`#<Thread:/home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:146 run> terminated with exception (report_on_exception is true):                                                             Traceback (most recent call last):                                                                                              7: from /home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:146:in `block (2 levels) in create_resources'                                                                                                     6: from /home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:448:in `wait_for_ssh'                                                                                                                             5: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:110:in `timeout'                                     4: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `catch'                                        3: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `catch'                                        2: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'                               1: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'                     /home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:449:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)                                                                    #<Thread:/home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:146 run> terminated with exception (report_on_exception is true):                                                             Traceback (most recent call last):                                                                                              7: from /home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:146:in `block (2 levels) in create_resources'                                                                                                     6: from /home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:448:in `wait_for_ssh'                                                                                                                             5: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:110:in `timeout'                                     4: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `catch'                                        3: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `catch'                                        2: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'                               1: from /usr/share/rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'                     /home/xx/.rvm/gems/ruby-2.7.2/gems/hetzner-k3s-0.3.7/lib/hetzner/k3s/cluster.rb:449:in `block in wait_for_ssh': undefined method `[]' for nil:NilClass (NoMethodError)    `

I tried with 6 servers and it worked well. :)

**Comment by vitobotta** [comment]
Hi!

Is it a new Hetzner account? If yes you may still have a low limit to the number of servers that you can create. So you need to contact support to raise the limit if that's the case.

**Comment by pucilpet** [comment]
No, it's a very old account. But have not used cloud services a lot. Not a big problem for me but just thought I should report it:)

**Comment by vitobotta** [comment]
If you have never asked them to raise your limit it should be still in place. I had the same before, now my limit is 25 servers so I don't have that problem anymore. You can check your limits from the console. Can you confirm that your limit is 8?

**Comment by pucilpet** [comment]
My limit was actually 10 but I had a few other servers running. Thanks for the assist!

**Comment by vitobotta** [comment]
Np. I'm closing this but feel free to reopen or open another one if you run into issues.
