### ISSUE TITLE
HCLOUD_TOKEN issue

### ISSUE THREAD

**Issue by dyipon** [vitobotta/hetzner-k3s#147]
Hi,

i set the HCLOUD_TOKEN to the correct value, and set the `hetzner_token: ""` in the yaml, but when I try to create cluster I get the next error message:
`Validating configuration...Cannot fetch server types with Hetzner API, please try again later`

doc says the next _"If you don't want to specify the Hetzner token in the config file (for example if you want to use the tool with CI), then you can use the HCLOUD_TOKEN environment variable instead, which has predecence.", so I think it should work.

What the correct way to use the env variable as token?

thanks

**Comment by vitobotta** [comment]
Hi, this has been reported in https://github.com/vitobotta/hetzner-k3s/issues/145 already. For the time being please set the token in the file, I will fix it as soon as I have a chance.

**Comment by dyipon** [comment]
sorry, closing this issue

**Comment by vitobotta** [comment]
No problem :)
