### ISSUE TITLE
How to contribute to wiki?

### ISSUE THREAD

**Issue by chrisjsimpson** [vitobotta/hetzner-k3s#149]
There's some edits* I'd like to make to: https://github.com/vitobotta/hetzner-k3s/wiki/Tutorial:---Setting-up-a-cluster

I know how to do usual PRs, but not PRs on Github wiki system. Is it different?

Perhaps some settings need to be changed to allow contributors?

*e.g. from `hetzner-k3s create-cluster` to `hetzner-k3s create` etc.

**Comment by vitobotta** [comment]
HI! Thanks for being available to contribute :) Maybe the easiest is if you share the updated copy in a gist for now and I will update the wiki. Is it ok for you? :)

**Comment by vitobotta** [comment]
Hi, feel free to open a PR for this. Maybe it's better to keep the WIKI pages in the repo.

**Comment by vitobotta** [comment]
I migrated the single Wiki page currently available to the repo in the /wiki directory. I've also fixed a few things. Feel free to open a PR if you want to improve it since it's now easier. :)
