### ISSUE TITLE
"status": "Failure",   "message": "Unauthorized",   "reason": "Unauthorized",   "code": 401

### ISSUE THREAD

**Issue by slackarea** [vitobotta/hetzner-k3s#16]
Hello vito!

First of alla your script works like a charme!!! It's magic!

After a successful installation I can't login in rancher web app.

When I am going to https://<load balancing IP>:6443/ I see this message.

What's wrong in my cabernets cluster?

Thank you very much for your work!!!

**Comment by slackarea** [comment]
My fault! Now with rancher work like a charm!

**Comment by vitobotta** [comment]
Awesome, glad you got it working :)
