### ISSUE TITLE
X509: Certificate is valid for ...

### ISSUE THREAD

**Issue by EnricoMessall** [vitobotta/hetzner-k3s#160]
When i create the cluster for a private network i can't access the logs of a pod from the master because im getting the X509: Certificate is valid for ... which not includes my subnet domains. I looked into the k3s.service file of the master and the subdomain is included there as tls-san and the secrets/k3s-serving also contains it but maybe it is missing in the certificate.

**Comment by vitobotta** [comment]
Can you clarify? You don't need to connect to the cluster from a session on the master, if that's what you mean. You can connect to the cluster using the kubeconfig that is automatically created for you in the location you specify in the config file.

**Comment by EnricoMessall** [comment]
Maybe i did something wrong here wen i created a cluster by myself last year but in this cluster i could connect through a tunnel server via ssh to the console of lets name it "master-1" and there just use `kubectl logs pod-xyz` to get to output of the wanted pod, like i can use `kubectl get pods --all-namespaces` or simiular. With hetzner-k3s this working for `kubectl get pods` but using for example `kubectl logs hcloud-cloud-controller-manager-847c54d774-wccx8` returns 

`Error from server: Get "https://10.x.xx.x:10250/containerLogs/kube-system/hcloud-cloud-controller-manager-847c54d774-wccx8/hcloud-cloud-controller-manager": x509: certificate is valid for 127.0.0.1, xxx.xxx.xx.xx, xxx.xxx.xx.xx, not 10.x.xx.x`

where "10.x.xx.x" is the address of the master node and the "xxx.xxx.xx.xx" the public address of the worker node where the pod is running on.

I also tried to do the same with the server i run the configuration on with
`kubectl config use-context <cluster_name>` 
and then
`kubectl logs hcloud-cloud-controller-manager-847c54d774-wccx8`

and it also not works.

**Comment by vitobotta** [comment]
I still don't understand why you are trying to connect to the cluster through the master via SSH. You don't need to do that and you are not supposed to do that. Like I said you can use the kubeconfig to connect to the cluster from your computer, not from the master. For example if you do **on your computer**

```bash
export KUBECONFIG=<location of the kubeconfig specified in the config file>
```

Then you can run kubectl commands against the cluster from your computer.

**Comment by vitobotta** [comment]
So you want to access the cluster from another server, not your computer, right?

Try coping the kubeconfig file that hetzner-k3s creates to the tunnel server, and using that kubeconfig from there. It should work. The important thing is that you use the kubeconfig created by the tool. Does it work that way?

Not sure though why some commands work the way you were accessing the cluster while others do not.

**Comment by EnricoMessall** [comment]
The tunnel is the server were i created the cluster from and the kubeconfig is stored on this server, its not working. Also checked that i can use the `kubectl config use-context <cluster_name>` and that worked and said it switched to the cluster but the command still fails. I only can imagine that it has a problem with using it inside the subnet because it then its not making use of the public ips for the request. But why it is working for all other commands then i also can't understand ^^

**Comment by EnricoMessall** [comment]
Everything like apply, delete, get is working like usual. For now i only had it on the logs command, yes.

**Comment by vitobotta** [comment]
LOL this is super weird. Have you tried with multiple workloads to see if it's an issue specific to the one you are testing with?

**Comment by EnricoMessall** [comment]
I tried some things since monday with some multiple setups of the cluster but logs always wouldn't work. I also tested it right now with my privat computer and the kubeconfig. It always prints out this error. Actually it is giving me the error not 10.1.20.1 on my private computer :|

**Comment by vitobotta** [comment]
Can you try creating another cluster in a different project and see if you run into the same issue? Trying to understand if something is wrong with this specific cluster. I have never come across this kind of issue unfortunately.

**Comment by EnricoMessall** [comment]
It seems to be the network of the clusters i created the last days. Without setting the network to use it works again. Maybe its a problem that the network has used 10.1.0.0/16 and not 10.0.0.0/16 ?

**Comment by vitobotta** [comment]
Oh wait!! I missed that bit. Yes at the moment the network is expected to have a subnet 10.0.0.0/16 in the firewall. Sorry about that, I should have read more carefully. For the time being can you please update the firewall manually and allow all traffic on your subnet? I will make the subnet configurable in the tool one of these days. Please try updating the firewall that way and let me know if you still have the same problem.

**Comment by vitobotta** [comment]
I have released v1.0.9 which allows you to customize the subnet for the private network. So please upgrade and give it a try. :)

**Comment by EnricoMessall** [comment]
I found out the script also has a problem to start the script with the private network from 10.1 or 10.3 might it be a problem that https://github.com/vitobotta/hetzner-k3s/blob/main/templates/worker_install_script.sh uses 10.0.0.1 to get the network interface and should instead use the 10.1 or 10.3 for example? At that point of starting the k3s-agent is stucked.

**Comment by vitobotta** [comment]
Ah yeah, I forgot about the initialization scripts. I will look into it tonight.

**Comment by EnricoMessall** [comment]
Beautiful, v1.1.0 fixed the problem with kubectl logs, thanks alot for the quick help :D

**Comment by vitobotta** [comment]
Np 👍

**Comment by EnricoMessall** [comment]
Hey @vitobotta i don't actually know if it is a problem of the firewall because it sometimes happen also with a mostly complete made open firewall but when i scale multiple workers (nearly always happens when having 3 workers) in the private network one hcloud-csi-node has an ImagePullBackOff saying it can not pull the image all other csi-nodes however can pull the image and starting just normal but one gives me `Error from server (BadRequest): container "csi-node-driver-registrar" in pod "hcloud-csi-node-5rfsk" is waiting to start: trying and failing to pull image`.

I haven't found an actual cause atm. Maybe you can find something in the scripts that might cause that?
