### ISSUE TITLE
Strange problems with ip adusting to nodes and therefor image pulling

### ISSUE THREAD

**Issue by EnricoMessall** [vitobotta/hetzner-k3s#161]
Hey i don't actually know if it is a problem of the firewall because it sometimes happen also with a mostly complete made open firewall but when i scale multiple workers (nearly always happens when having 3 workers) in the private network one hcloud-csi-node has an ImagePullBackOff saying it can not pull the image all other csi-nodes however can pull the image and starting just normal but one gives me `Error from server (BadRequest): container "csi-node-driver-registrar" in pod "hcloud-csi-node-5rfsk" is waiting to start: trying and failing to pull image`.

Also Ingress-Nginx Deployments from Kubernetes then getting ErrImagePull saying they can't find the images (That also always happens on the server where the csi-node fails)

I haven't found an actual cause atm. Maybe you can find something in the scripts that might cause that?

Addition: Tested it also on a cluster with 0.0.0.0/0 firewall and new private network, also exists there, since hcloud controller was on that node also hcloud controller failed to pull the images needed

**Comment by EnricoMessall** [comment]
Also i could find out that the container somehow uses sometimes different IPS for Pods, looks like fetching image on worker--3 is working with the private subnet address but not with the internal 10.244.1.2
![csi-node-failing](https://user-images.githubusercontent.com/62150527/219652051-0e1acffc-10f2-4243-b6f5-0e95c5d1ec97.png)

**Comment by vitobotta** [comment]
It happened to me once but I didn't investigate further because deleting the containers affected resolved the issue, i.e. the image was then pulled fine. I can't remember the details but I think I found some references from others who had a similar issue with k3s but I am not sure

**Comment by vitobotta** [comment]
Can you try to pull the image locally? if it works, can you try pulling it manually on the worker node with the problem?

**Comment by EnricoMessall** [comment]
Locally everything is working. On the server i actually get 

docker pull registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0

Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>403 Forbidden</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Forbidden</h1>\n<h2>Your client does not have permission to get URL <code>/v2/sig-storage/csi-node-driver-registrar/manifests/v2.7.0</code> from this server.</h2>\n<h2></h2>\n</body></html>\n"

Thats interesting xD

**Comment by vitobotta** [comment]
which is the domain it's pulling from?

**Comment by vitobotta** [comment]
I wonder if your IP has been banned for some reason. It's weird, but the 403 is also weird. Can you set up tinyproxy on a temporary server in the same project (the smallest instance is fine) and try to pull the image from the problematic node but using the other one as proxy? to see if it's the IP that is restricted from pulling for some reason

**Comment by EnricoMessall** [comment]
But that wouldn't make a lot of sense i guess because the ip is changing sometimes since i tried it some times with new cluster having different ipv4 addresses so i never had the same ips.

**Comment by EnricoMessall** [comment]
> which is the domain it's pulling from?

If im getting this right registry.k8s.io is a github package repository by kubernetes themself

**Comment by vitobotta** [comment]
When you create a server, Hetzner tries to reuse IPs you have already used in your account if available. So it may happen that you get the same ip when creating a new server, so if it was banned somehow, it will still be banned with the new server

**Comment by EnricoMessall** [comment]
Okay thats good to know. I actually not worked with tinyproxy until now but i tested curl with it and looked if its working and it seems like it worked and i added a docker config for proxy like it is described by docker and it's still giving me the same Forbidden Response.

**Comment by vitobotta** [comment]
Not much I can do unfortunately as I don't control those registries. It's annoying. It happened to me 1-2 times months ago

**Comment by EnricoMessall** [comment]
Yea alright might be a solution to have my own versions of the scripts for the moment on a private repository thats accessible fully for me. Im closing this issue for now and will write here if there are some changes in the future.

**Comment by cm-andrews** [comment]
having the same issue in which kube-system hcloud-csi-node-xyz is in a constant ImagePullBackOff state...
describe shows
` Normal   BackOff    5m2s (x3224 over 10h)  kubelet  Back-off pulling image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0"`
very weird.

**Comment by EnricoMessall** [comment]
@cm-andrews Yea i found that pulling an image from docker hub has also an 401 3 times on trying to pull a manifest. But they 4 attempt worked. However the Google Cloud Repository on registry.k8s.io only pull ones an fails and is finished. I already created an issue in csi-node-driver-registrar but the guy from google just answered for me it is working, but i wrote him it is also working on most of the nodes and my local machine... so atm i don't see another way then creating one versions of everything by myself and have it in my private repo including creating a own copy of hetzner-k3s

**Comment by vitobotta** [comment]
> @cm-andrews Yea i found that pulling an image from docker hub has also an 401 3 times on trying to pull a manifest. But they 4 attempt worked. However the Google Cloud Repository on registry.k8s.io only pull ones an fails and is finished. I already created an issue in csi-node-driver-registrar but the guy from google just answered for me it is working, but i wrote him it is also working on most of the nodes and my local machine... so atm i don't see another way then creating one versions of everything by myself and have it in my private repo including creating a own copy of hetzner-k3s

Rather than pushing the images to some other registry, have you tried with a registry cache/mirror?

**Comment by EnricoMessall** [comment]
Good point. I tried it yesterday and for whatever reason I can't create a pull through cache for registry.k8s.io, on the Docker Hub registry a pull through cache worked.

**Comment by EnricoMessall** [comment]
Its actually completely over now. Even the master with no other worker (autoscaling) fails to fetch from registry.k8s.io and therefor couldn't fetch the auto scaler also

**Comment by vitobotta** [comment]
> Its actually completely over now. Even the master with no other worker (autoscaling) fails to fetch from registry.k8s.io and therefor couldn't fetch the auto scaler also

In which locations did you create your servers? I tried now with a cluster with a single master in falkenstein and 3 nodes in nuremberg and it worked fine, no errors pulling images

**Comment by EnricoMessall** [comment]
I create them in Nuremberg

**Comment by apricote** [comment]
Hi all,

@hetznercloud employee here. We know of multiple cases where our IPs have been sporadically blocked by Google & AWS. It would be great if you could send any affected IPs and the endpoints where this happens (registry.k8s.io in this case) to our support: https://console.hetzner.cloud/support
