### ISSUE TITLE
hetzner-k3s: command not found, library not loaded on macOS M1

### ISSUE THREAD

**Issue by mike667** [vitobotta/hetzner-k3s#162]
Hello. I want to try this tool but cannot start with it.

I use macOS Ventura 13.2.1 (22D68).

I tried to install it via brew
```bash
brew install vitobotta/tap/hetzner_k3s
```

But I got an error. **zsh: command not found: hetzner_k3s**

After I tried to find the package in Cellar and run, I got: 
```bash
dyld[16663]: Library not loaded: /opt/homebrew/opt/gmp/lib/libgmp.10.dylib
  Referenced from: <40FA0D73-E8E3-356F-8E11-3745FD128859> /opt/homebrew/Cellar/hetzner_k3s/1.1.0.reinstall/bin/hetzner-k3s
  Reason: tried: '/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/usr/local/lib/libgmp.10.dylib' (no such file), '/usr/lib/libgmp.10.dylib' (no such file, not in dyld cache)
```

After I tried the [manual install](https://github.com/vitobotta/hetzner-k3s#apple-silicon--m1) for M1, but also got these errors, but those helpers libraries mentioned in README already installed via brew.

Could you help me?

Best regards

**Comment by vitobotta** [comment]
Homebrew is recommended because it installs the dependencies automatically. To me it seems your homebrew installation may have some issues. What do you get if you run `brew doctor`?

**Comment by mike667** [comment]
Fixed:
1. brew install pcre
2. brew install gmp
3. Run the command as  /opt/homebrew/bin/hetzner-k3s releases

**Comment by mike667** [comment]
> Homebrew is recommended because it installs the dependencies automatically. To me it seems your homebrew installation may have some issues. What do you get if you run `brew doctor`?

Your system is ready to brew.

**Comment by vitobotta** [comment]
Weird. I am on Ventura as well on both M1 and Intel macs and didn't run into any issues with the regular install. Does the tool work now?

**Comment by vitobotta** [comment]
I see. Thanks for letting me know, I will update the formula with those dependencies :)

**Comment by vitobotta** [comment]
I am leaving it open as a reminder for myself :)

**Comment by janhkrueger** [comment]
Just wanted to add, had the same issue.
Thanks to @mike667 I could also solve this easily.

Fresh brew installation so I would also suggest that prce and gmp should added to the dependency list.

**Comment by mimlrd** [comment]
Same issue as @mike667 and @janhkrueger. I'm on an intel Mac with a fresh OS installed.
Thanks to @mike667 for the solution.

**Comment by vitobotta** [comment]
Hi, sorry for the delay. I have updated the formula with the missing packages. Thanks for reporting it :)

**Comment by vitobotta** [comment]
I have released a new version btw.
