### ISSUE TITLE
[QUESTION] kubectl error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by marc0olo** [vitobotta/hetzner-k3s#164]
Hi @vitobotta,

almost exactly 1 year ago I created my cluster using the docker image of version v0.5.3 and today we experienced issues with our cluster, mainly with the LoadBalancer as the targets of the ingress were gone.

I recognized I cannot access my cluster from outside anymore and I assume some certificate expired:

```
kubectl get pods -n prod
error: You must be logged in to the server (Unauthorized)
```

I can access the master node directly and use kubectl there. As far as I know kubeadmin has not been installed, right?

Can you somehow help me out or at least tell me if my assumption is correct and maybe also give a hint how to solve the issue?

I know this is not an issue of this tool, but help is really appreciated. I want to get the setup healthy again.

Thanks
Marco

**Comment by marc0olo** [comment]
meanwhile I updated k3s using the old v0.5.3 version and added a new worker node. the loadbalancing issue is now resolved. but I still cannot access the cluster from outside (same error as above)

wondering how to solve that 🤔

**Comment by TitanFighter** [comment]
1. ssh to worker and check if certificates have expired: `openssl s_client -connect localhost:6443 -showcerts < /dev/null 2>&1 | openssl x509 -noout -enddate`

If yes:

2.
```
# Stop K3s
systemctl stop k3s

# Rotate certificates
k3s certificate rotate

# Start K3s
systemctl start k3s
```

However, [according to this page](https://docs.k3s.io/cli/certificate) certificates automatically should be renewed:
> K3s client and server certificates are valid for 365 days from their date of issuance. Any certificates that are expired, or within 90 days of expiring, are automatically renewed every time K3s starts.

3. `scp root@WORKER_IP:/etc/rancher/k3s/k3s.yaml ./`
4. export KUBECONFIG=./kubeconfig

Now everything should be ok.
