### ISSUE TITLE
Pass API Token as Environment Variable

### ISSUE THREAD

**Issue by deveth0** [vitobotta/hetzner-k3s#17]
Hey, thank you for this awesome tool, saved me a lot of headache :)

I'd like to run the tool from a CI to create multiple clusters. Is there any way to pass the API Token as Environment Variable (HCLOUD_TOKEN) instead of the config?

Cheers

**Comment by vitobotta** [comment]
Hi, that's actually a pretty good idea. I hadn't thought about that. Adding it to my nodes of things to add :) I'll update this when it's done. I am quite a bit busy with my day job at the moment but I will add it as soon as I can.

**Comment by deveth0** [comment]
awesome, thanks! My current workaround is using sed to modify the file, works for now :)

**Comment by vitobotta** [comment]
👍

**Comment by vitobotta** [comment]
Hi @deveth0 - I've added the support for the HCLOUD_TOKEN env var in 0.4.0. Thanks for the suggestion!

**Comment by deveth0** [comment]
Haha, that's `as soon as I can`? Awesome, thanks!

**Comment by deveth0** [comment]
Tested and confirmed!
