### ISSUE TITLE
upgrade path for new CSI plugin

### ISSUE THREAD

**Issue by quorak** [vitobotta/hetzner-k3s#174]
```
...done.

Creating secret for Hetzner Cloud token...
secret/hcloud configured
...secret created.

Deploying Hetzner Cloud Controller Manager...
serviceaccount/cloud-controller-manager unchanged
clusterrolebinding.rbac.authorization.k8s.io/system:cloud-controller-manager unchanged
deployment.apps/hcloud-cloud-controller-manager unchanged
...Cloud Controller Manager deployed

Deploying Hetzner CSI Driver...
storageclass.storage.k8s.io/hcloud-volumes unchanged
serviceaccount/hcloud-csi-controller unchanged
clusterrole.rbac.authorization.k8s.io/hcloud-csi-controller unchanged
clusterrolebinding.rbac.authorization.k8s.io/hcloud-csi-controller unchanged
service/hcloud-csi-controller-metrics configured
service/hcloud-csi-node-metrics unchanged
deployment.apps/hcloud-csi-controller unchanged
daemonset.apps/hcloud-csi-node unchanged
The CSIDriver "csi.hetzner.cloud" is invalid: spec.fsGroupPolicy: Invalid value: "File": field is immutable
Failed to deploy CSI Driver:
The CSIDriver "csi.hetzner.cloud" is invalid: spec.fsGroupPolicy: Invalid value: "File": field is immutable
```

Hey there, I recently upgraded the hetzner-k3s binary.
After using it with a existing cluster (>1year old) I got the above error.
I read its probably due to a new CSI driver by hetzner. 

* Do you have a upgrade path available?
* Can we provide one without loosing the pvc's? 

much appreciated, best

**Comment by vitobotta** [comment]
Hi, I will try to release a new version with the latest CSI driver tomorrow.

**Comment by quorak** [comment]
followed the manual upgrade from hetzner csi description. works now

**Comment by vitobotta** [comment]
Glad you sorted it. I haven't had a chance to release a new version yet.

**Comment by sananguliyev** [comment]
@vitobotta is this still issue?

**Comment by vitobotta** [comment]
> @vitobotta is this still issue?

What do you mean? I have updated the version of the manifest in the latest release and also made it configurable.

**Comment by sananguliyev** [comment]
I currently set `csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml"` but this error `The CSIDriver "csi.hetzner.cloud" is invalid: spec.fsGroupPolicy: Invalid value: "File": field is immutable`

**Comment by sananguliyev** [comment]
In case someone has the same issue, deleting and applying CSI driver worked for me:

```
kubectl delete -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml
kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml
```

**Comment by vitobotta** [comment]
> In case someone has the same issue, deleting and applying CSI driver worked for me:
> 
> ```
> kubectl delete -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml
> kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml
> ```
> 
> P.S. version could be different in your case.

Did the delete command actually delete all the defined resources? This is weird because it should affect the persistent volumes you have I think. Anyway glad you got it working :)

**Comment by sananguliyev** [comment]
It was my test cluster. I just did not find a proper way to do it, and tried this, but everything worked fine and all the volumes were in place with existing data after delete and apply.

**Comment by vitobotta** [comment]
> It was my test cluster. I just did not find a proper way to do it, and tried this, but everything worked fine and all the volumes were in place with existing data after delete and apply.

Cool 👍
