### ISSUE TITLE
Failed deployment and connection refused on load balancer port 6443 in Kubernetes

### ISSUE THREAD

**Issue by CapitanMurloc** [vitobotta/hetzner-k3s#180]
I deployed using the guide and for some unknown reason the load balancer had to have removed port 6443.

Error: Kubernetes cluster unreachable: Get "https://167.235.111.69:6443/version": dial tcp 167.235.111.69:6443: connect: connection refused

**Comment by vitobotta** [comment]
Is the load balancer healthy in the Hetzner control panel?

**Comment by CapitanMurloc** [comment]
It happens when you install ingress, you no longer have access to port 6443. I don't know if there is some step that needs to be configured manually?

**Comment by CapitanMurloc** [comment]
I've investigated the issue further and found out that when you configure the load balancer in the daemonset and set the same name as the load balancer that is created when deploying the cluster, this causes the original load balancer to be overwritten, making the port 6443 disappear. At first, I didn't think it was necessary to have two separate load balancers, but after analyzing the situation, I've come to the conclusion that it is indeed a requirement to have them separated in order to avoid this kind of conflict.
