### ISSUE TITLE
Setup with multiple Clusters and shared Services like VPN and Monitoring

### ISSUE THREAD

**Issue by creib** [vitobotta/hetzner-k3s#181]
Hello,
I have a question. As far as I am informed, it is not possible at Hetzner to communicate across project boundaries in the network.

I wanted to create three projects:
- Project-Test-Kubernetes Cluster (with Prometheus for Test and Production).
- Project-Production-Kubernetes Cluster
- Project VPN Server

SSH access to the Kubernetes clusters, any access to the test cluster should be protected via the VPN. Therefore, I would need to access the other two projects from VPN-Project.

Currently, the only option I see is to combine all three projects into one project and deploy two clusters into one Hetzner project.

Am I overlooking another option here?
Thank you very much for your help.

**Comment by vitobotta** [comment]
You can use the `ssh_allowed_networks` and `api_allowed_networks` to restrict the access to the cluster nodes and API server so that you can only access them via VPN. Does that help?

**Comment by creib** [comment]
Thanks, this helps. But still a question is: If I want to run Grafana/Prometheus on one cluster, and I want to monitor applications, running on another cluster, I would have to either put both clusters into one project or put everything on one cluster. So what is the better choice in this case?

**Comment by vitobotta** [comment]
I haven't used Prometheus/Grafana to manage other clusters so far, but just the cluster they are installed in, so am not sure about this

**Comment by creib** [comment]
Ok, it makes sense to install two instances of Grafana/Prometheus, one for each cluster. Do have an idea, how I can setup one VPN Server over which I would be able to connect to Nodes of both clusters? As far as I see, I have to establish two VPN Server, one for each Project.

**Comment by vitobotta** [comment]
I've only used OpenVPN and Wireguard in the past but not with Kubernetes. Why do you need to access the nodes? For maintenance or else?

**Comment by creib** [comment]
Yes, and I would like to have an additional server in each project to host a database. I think it is a good idea to not run the database on the cluster. And it should be in the same project so It can be accessed by the services on the cluster and by me, using vpn.

**Comment by vitobotta** [comment]
What kind of database? Running databases on Kubernetes has been fine for quite sometime now. The problems with storage from the early days are gone and there are some operators for the major databases that make life a lot easier and leverage the high availability of Kubernetes. So I would reconsider running databases externally if it's an additional thing you need to maintain yourself. :)

**Comment by creib** [comment]
We need to use a MongoDB

**Comment by vitobotta** [comment]
OK, I am not familiar with it so I can't recommend operators etc for it.

**Comment by creib** [comment]
Thanks for your help. I will give it a try with mongodb on the cluster.
