### ISSUE TITLE
clarify use of load-balancer.hetzner.cloud/uses-proxyprotocol: "false"

### ISSUE THREAD

**Issue by kunoSchlonz** [vitobotta/hetzner-k3s#182]
Hi,

is started to create a simple "test" cluster according to your recommendations
but i did not use a hostname for the ingress controller in order to just use the xyz.IP.nip.io adressess
but used the `load-balancer.hetzner.cloud/uses-proxyprotocol: "true"` as recommended.
I deployed the hello-world rancher image (according the wiki).
Bit calling the URL leads into the situation that the nginx always responds with 400.
then i set  `load-balancer.hetzner.cloud/uses-proxyprotocol: "false"` and voila it works.

As im not an expert for nginx, would you mind to give some more explanation here?

Thanks a lot for your effort with that project.

**Comment by creib** [comment]
Hi, you have to set the use-proxyprotocol=true on the ingress definition as well. Check this discussion: [178](https://github.com/vitobotta/hetzner-k3s/discussions/178
)

**Comment by vitobotta** [comment]
You probably didn't follow the tutorial correctly because that includes configuring the proxy protocol in the Nginx configmap as well, which solves this issue. Anyway there's a separate discussion for this linked to by @creib so I am closing.
