### ISSUE TITLE
autoscaling + label not working

### ISSUE THREAD

**Issue by rsidhaarth** [vitobotta/hetzner-k3s#187]
Hi,

I tried to create a pool with autoscaling + label, and it is not detected when the cluster is made.

![image](https://user-images.githubusercontent.com/16856248/227721320-5b7c279a-324e-4709-b822-115669619ef7.png)

Please let me know what is wrong or whether it is an issue.

**Comment by vitobotta** [comment]
What is not detected? Labels and taints don't apply to autoscaled node pools because they are not supported by the cluster autoscaler.

**Comment by vitobotta** [comment]
It's a limitation of the cluster autoscaler. Closing since there isn't much I can do with my tool about it.
