### ISSUE TITLE
network issue 

### ISSUE THREAD

**Issue by rsidhaarth** [vitobotta/hetzner-k3s#188]
Use Case:

I want another cluster of specs that wish to communicate with K8s. So I want to have 2 subnets. 

1 Subnet for K8s 
1 Subnet for another cluster

Issue 1 - In the config file, I gave 10.0.0.0/24 and created the cluster. It does not allow me to create another subnet of a different range so both can communicate. In Hetzner, if you make a smaller subnet, you can keep attaching more subnets to the same network.

Issue 2 - I also tried creating network 1st manually and assigned two different subnets.

![image](https://user-images.githubusercontent.com/16856248/227741099-72aee172-1a7f-4355-a350-6f7da7e64a40.png)

But the resources are getting assigned to both the subnets, even in the network I have mentioned. 

![image](https://user-images.githubusercontent.com/16856248/227741150-38607d13-83f7-41bf-be0a-cb8c80b39a5e.png)

**Comment by vitobotta** [comment]
1 - not sure what you are asking from the tool, can you clarify?
2 - we don't have control on how Hetzner assigns servers to subnets. We can only specify the network when we create a server, see https://docs.hetzner.cloud/#servers-create-a-server

**Comment by vitobotta** [comment]
The network ID that we can set via API when creating a server is the numeric ID of the network, not  the range, and it's not possible to specify the subnet when creating a server, at least not yet. Closing since I can't do anything about it for now.
