### ISSUE TITLE
Allow to configure private ssh key

### ISSUE THREAD

**Issue by deveth0** [vitobotta/hetzner-k3s#19]
Right now the tool fallbacks to the ssh keys provided by the ssh agent.
This can become complicated when running on a CI server, as the agent does not necessarily contain the correct keys.
It would be great to have an option that sets the private ssh key to be used (ideally both as value in the config and as env variable).

**Comment by vitobotta** [comment]
Done in v0.4.1. Feel free to reopen if you have problems with it. Thanks for the suggestion! :)

**Comment by deveth0** [comment]
Yay thy
