### ISSUE TITLE
Persistent Volume Problem

### ISSUE THREAD

**Issue by mamycan** [vitobotta/hetzner-k3s#197]
Hello, I'm new on HetznerCloud.
I've created this storage but couldn't see any storage on Hetzner console and the pod didn't work.
Do I need to prepare or manual create storage?
Thanks.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: hcloud-volumes

**Comment by vitobotta** [comment]
Hi, do you see the PVC as Kubernetes resource? If yes use the `describe` command to see what's wrong with the volume. Also check the logs of the CSI controller in `kube-system`.

**Comment by mamycan** [comment]
> Hi, do you see the PVC as Kubernetes resource? If yes use the `describe` command to see what's wrong with the volume. Also check the logs of the CSI controller in `kube-system`.

How Can I create a volume for all pods?

  Normal   NotTriggerScaleUp   7m16s               cluster-autoscaler       pod didn't trigger scale-up: 1 persistentvolumeclaim "plyapi" not found, 1 max node group size reached
  Warning  FailedAttachVolume  7m1s                attachdetach-controller  Multi-Attach error for volume "pvc-d5619174-e5a1-469e-8c4e-bde2f95aacc6" Volume is already used by pod(s) php-7497dfd66f-lh575
  Warning  FailedMount         27s (x3 over 5m3s)  kubelet                  Unable to attach or mount volumes: unmounted volumes=[plyapi],

**Comment by vitobotta** [comment]
The default storage class if for ReadWriteOnce block storage volumes. If you need a shared filesystem you need to use something like NFS or similar, which is out of scope for this tool.
