### ISSUE TITLE
chmod on kubeconfig

### ISSUE THREAD

**Issue by vishr** [vitobotta/hetzner-k3s#20]
Thanks for your project, it saved me a lot of time.

I got a `WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ~/kubeconfig.`, which I fixed using `chmod go-r ~/.kube/config`. May be you can implement something similar while write file.

**Comment by vitobotta** [comment]
Done in v0.4.1. Feel free to reopen if you have problems with it. Thanks for the suggestion! :)
