### ISSUE TITLE
Tutorial wiki page missing

### ISSUE THREAD

**Issue by carstenblt** [vitobotta/hetzner-k3s#206]
Your README reads `Also see this [wiki page](https://github.com/vitobotta/hetzner-k3s/wiki/Tutorial:---Setting-up-a-cluster) for a tutorial on how to set up a cluster with the most common setup to get you started.` - however the page is missing.

**Comment by vitobotta** [comment]
Sorry, I fixed the link https://github.com/vitobotta/hetzner-k3s/blob/main/wiki/Setting%20up%20a%20cluster.md
