### ISSUE TITLE
missing documentation on how to specify a target project

### ISSUE THREAD

**Issue by level420** [vitobotta/hetzner-k3s#22]
I've tried to read thoroughly the documentation, but could not find where to specify the Hetzner cloud project where the cluster will be provisioned, until I noted that the `hetzner_token` in the YAML config file is project related.

It may be good to have this documented in the README.md

Looking forward to test this for the first time! Thany you @vitobotta !

**Comment by vitobotta** [comment]
Hi! And thanks :)

The README says:

"an Hetzner Cloud token: for this you need to create a project from the cloud console, and then an API token with both read and write permissions (sidebar > Security > API Tokens); you will see the token only once, so ensure you take note of it somewhere safe"

Is it not clear enough? :)
