### ISSUE TITLE
Support External Database datastores

### ISSUE THREAD

**Issue by Shakahs** [vitobotta/hetzner-k3s#224]
K3S supports [using SQL databases](https://docs.k3s.io/datastore/ha) for master data instead of etcd, and I find managed Postgres ([CrunchyData](https://www.crunchydata.com/products/crunchy-bridge), [Neon.Tech](https://neon.tech/)) to be more attractive than etcd in this use case. 

I was able to create a Postgres-backed hetzner-k3s cluster by just adding the K3S_DATASTORE_ENDPOINT environment variable to master_install_script.sh and recompiling hetzner-k3s.  

`curl -sfL https://get.k3s.io | K3S_DATASTORE_ENDPOINT="postgres://xxxxx:xxxxx@ep-fancy-rice-603429.us-east-1.aws.neon.tech/neondb"  INSTALL_K3S_VERSION...`

No other changes were required. I now have 3x K3S masters _without_ the etcd role:
```
~/d/p/K3SCluster  KUBECONFIG=kubeconfig kubectl get nodes                                                                                             (base) 394ms  Sat Jun  3 20:48:25 2023
NAME                          STATUS   ROLES                  AGE   VERSION
small-7cd4b7a55a25e0cb        Ready    <none>                 19m   v1.27.2+k3s1
k3s-ashburn-1-cpx11-master1   Ready    control-plane,master   21m   v1.27.2+k3s1
k3s-ashburn-1-cpx11-master2   Ready    control-plane,master   62s   v1.27.2+k3s1
k3s-ashburn-1-cpx11-master3   Ready    control-plane,master   57s   v1.27.2+k3s1
```

It would be nice if hetzner-k3s supported passing the necessary environment variables or configuration strings for external database support. 

Also, even-numbered master replica counts are valid here because Postgres ACID guarantees replace etcd consensus protocols. However hetzner-k3s doesn't allow setting an even number of masters.

**Comment by vitobotta** [comment]
I haven't implemented this yet because it hadn't been asked before and I actually find it easier not to have to introduce another dependency like Postgres etc, but I'll add it to my to-do list.

**Comment by Shakahs** [comment]
The hetzner-k3s configuration already allows users to provide additional configuration parameters for Kubernetes components (kubelet_args, kube_proxy_args, etc.). 

The simplest solution would be to follow this pattern and allow users to provide additional configuration parameters to K3S master setup.

**Comment by Shakahs** [comment]
Closing this in favor of the more general #229
