### ISSUE TITLE
Upgrade libssh2 dependencies to 1.11.0

### ISSUE THREAD

**Issue by quorak** [vitobotta/hetzner-k3s#225]
Newest libssh2 adds support for sk-ecdsa-sha2-nistp256 and sk-ssh-ed25519 keys.
Can we upgrade our binaries?

Much appreciated. Best

**Comment by vitobotta** [comment]
Why did you close it? :)

**Comment by quorak** [comment]
I did upgrade, but there was a lot more for https://github.com/spider-gazelle/ssh2.cr.git to make my yubikey working. 
But would be great if we take a look together.

**Comment by vitobotta** [comment]
I have updated the ssh2 shard and will include this change in the next release hopefully next week.
