### ISSUE TITLE
Adding baremetal / dedicated nodes

### ISSUE THREAD

**Issue by DaanVanVugt** [vitobotta/hetzner-k3s#230]
I am trying to add one of our dedicated nodes, and managed to register it, following guides:

- https://pet2cattle.com/2021/04/k3s-join-nodes
- https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch/

The node is listed in `kubectl get nodes`, but has a taint: `node.kubernetes.io/network-unavailable:NoSchedule`

This seems to be caused by

```
Warning  FailedToCreateRoute      4m42s (x123 over 65m)
 route_controller  (combined from similar events):
   Could not create route 377627a0-3d0b-4aa0-977a-b475189eb2c2 10.244.1.0/24
  for node benchy after 164.80536ms: hcloud/CreateRoute: hcops/AllServersCache.ByName: benchy hcops/AllServersCache.getCache: not found
```

which makes sense, since it is not a VPS and so the hcloud APIs will not like it.

Is there a way to prevent this taint from occurring? Or to manually make this route?

**Comment by vitobotta** [comment]
Can you see the dedicated node in the private network from one of the regular nodes? Converting this into a discussion since it's not an issue with the tool.
