### ISSUE TITLE
DNS for LoadBalancer API Server 

### ISSUE THREAD

**Issue by mgalesloot** [vitobotta/hetzner-k3s#238]
Would it be possible to specify a DNS for the Loadbalancer of the k8s api server, e.g. `k8s.example.com`? This DNS would then be added as a SAN (with the option --tls-san). 

This would allow us to make a DNS to the internal IP of the LoadBalancer, and hide the LoadBalancer from the public network. In combination with the Wireguard VPN the K8s API server cluster would be more secure.

**Comment by vitobotta** [comment]
It's doable, seems like a small change. Do you need it urgently? I am kinda busy with work at the moment

**Comment by mgalesloot** [comment]
Not urgently. I could also try it myself and send you a merge request.

**Comment by filviu** [comment]
Would it be possible to also add the private ip of the load balancer to the certificate ? 

I run a tailscale subnet router so I can access the private ip of the control plane load balancer but it doesn't work since it's not in the SAN:

1.2.3.4 is the public IP of the load balancer, I just replaced it for privacy. Also no idea where 10.43.0.1 is coming from...

```
couldn't get current server API group list: Get "https://10.0.0.5:6443/api?timeout=32s": tls: failed to verify certificate: x509: certificate is valid for 10.43.0.1, 10.61.0.2, 10.61.0.3, 10.61.0.4, 127.0.0.1, 1.2.3.4, ::1, not 10.61.0.5
```

**Comment by mgalesloot** [comment]
I think this is a good idea. The private ip of the load balancers should be trusted. I could add this in the current PR on this topic.

**Comment by vitobotta** [comment]
Thanks @mgalesloot if you can do a PR. I have been extremely busy and haven't had time lately for side projects because I am busy with the day job, preparing for a certification with offensive security and working on my own startup (dynasite.ai) at the same time 😓

**Comment by mgalesloot** [comment]
I have made a new PR: https://github.com/vitobotta/hetzner-k3s/pull/272

**Comment by vitobotta** [comment]
Closing since @mgalesloot 's PR has been merged 🎉
