### ISSUE TITLE
Improvement: HTTP.follow.get retries

### ISSUE THREAD

**Issue by michael-sayapin** [vitobotta/hetzner-k3s#24]
Thanks for the excellent repo!

A little improvement that could save a lot of time for those living in China or other oppressed countries, would be to add retry policy to `HTTP.follow.get` calls (or add an option for air-gapped installation).

Github calls mostly work, but `raw.githubusercontent.com` is typically either blocked outright or DNS poisoned, so we have to run Docker with `--network host` + `export https_proxy...` to have anything downloaded, but that also sometimes requires 10+ reruns of the script.

**Comment by vitobotta** [comment]
Done in v0.4.1. Feel free to reopen if you have problems with it. Thanks for the suggestion! :)
