### ISSUE TITLE
Allow custom configuration of firewall / disruption free updates

### ISSUE THREAD

**Issue by jrudolph** [vitobotta/hetzner-k3s#254]
Thanks for this great tool!

One problem that I encountered was that during an update, firewalls are reconfigured and any customization you might have made is lost. In my case I want to avoid the extra cost of the load balancer and therefore the cluster needs direct access to webserver ports. I can open up those ports but during each update the firewall config is updated first, so all access is denied until I can afterwards reenable my custom rules.

The easiest solution for me would be to introduce new command line arguments (or config) that control which aspects hetzner-k3s should (re)configure, e.g. `--no-firewall-update`. Would that make sense?

**Comment by vitobotta** [comment]
Hi, you can apply multiple firewalls to a server. So I'd try creating a separate, custom firewall with these extra rules.

https://docs.hetzner.com/cloud/firewalls/faq/#what-are-the-limitations-of-firewalls

**Comment by jrudolph** [comment]
That's great, I'll try that.
