### ISSUE TITLE
Similar using terraform 

### ISSUE THREAD

**Issue by gedw99** [vitobotta/hetzner-k3s#255]
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner

I habe not tried this but figured it’s useful to compare ..

**Comment by gedw99** [comment]
I assume that with terraform it’s easier to change the setup in that it will in theory do reconciliation.

**Comment by vitobotta** [comment]
Why did you open another issue? Please continue here https://github.com/vitobotta/hetzner-k3s/discussions/258.
