### ISSUE TITLE
Question: Is it possible create an HA cluster using only master nodes ? 

### ISSUE THREAD

**Issue by T-helper** [vitobotta/hetzner-k3s#26]
Is it possible to create small HA cluster from three master nodes, without specifiygn worker nodes, lets say i wish to add them later ? When i tried just not specifiing worker nodes, i've got an error says "Invalid node pools configuration"

**Comment by vitobotta** [comment]
Hi, the current setup assumes that you don't want to schedule workloads on the masters because that's recommended for production. However I can add an option for it so that it's customizable. I'll leave this open for now and let you know when it's done.

**Comment by vitobotta** [comment]
Done in v0.4.1. I added an option to schedule workloads on the masters. Feel free to reopen if you have problems with it. Thanks for the suggestion! :)
