### ISSUE TITLE
How to customise k3s installation writing yaml files into required directories?

### ISSUE THREAD

**Issue by vinnytwice** [vitobotta/hetzner-k3s#265]
@vitobotta Hi again. 
Sorry to bother again but apart from that wiki page I don't seem to find docs for hetzner-k3s.  

I'm looking into securing the cluster with PSA, Network policies etc etc, so I see that in the config.yaml file you can set `kube_api_server_args`, `kube_scheduler_args`, `kube_controller_manager_args`, `kube_cloud_controller_manager_args`, `kubelet_args`, `kube_proxy_args` to k3s, and looking into their CIS Hardening Guide and I see that you have to  pass different arguments (for instance to setup PSA) so in the cluster_config.yaml I use 
```
kube_api_server_args:
- admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml
```
but then how to actually write that psa.yaml file into that directory using hetzner-k3s? 
Is it a manual step I have to do for each machine or there is a way to pass `PodSecurity`, `NetworkPolicy` and other  yaml files during cluster creation?

Many thanks.
Cheers

**Comment by vinnytwice** [comment]
Hi Vito do you mean something like this?
```
post_create_commands:
  - cp psa.yaml /var/lib/rancher/k3s/server/
```

**Comment by vitobotta** [comment]
No, because those commands are run directly on the server. So you cannot copy a file like that. In a future release I will make it possible to specify files to transfer.

For now, the easiest way is to convert the content of the file to a base64 string and then add a post create command like:

```bash
- echo -n <base64 string> | base64 -d > /location/on/server/file.ext
```

**Comment by vitobotta** [comment]
> Oh I see, nice to know that this will be available. Any idea of when will it be available ? 

Not sure, I am quite busy at the moment and you are the first person asking this :)

>So as for now I should first base64 encode the yaml like
> 
> ```
> base64 -w 0 psa.yaml
> ```
> 
> and then dec ode it in the config.yaml
> 
> ```
> post_create_commands:
>   - echo -n '<base64 string>' | base64 -d > /var/lib/rancher/k3s/server/psa.yaml
> ```

yep, sounds correct. 

> 
> Did I get it correctly?
> 
> Also I guess that the correct way to pass the arguments is as k3s has it in their page instead of how passed it in my code snippet above right?
> 
> ```
> kube-apiserver-arg:
>   - 'admission-control-config-file=/var/lib/rancher/k3s/server/psa.yaml'
> ```

I can't remember if you need the quotes around it

**Comment by vinnytwice** [comment]
Thank you very much for your help Vito. I'm just getting into securing Kubernetes clusters and there are a lot of things that until now I haven't looked into. I still have very much to learn about it, so some things are not obvious for me yet. 
Thank you again form being so available.
Ciao

**Comment by vitobotta** [comment]
> Thank you very much for your help Vito. I'm just getting into securing Kubernetes clusters and there are a lot of things that until now I haven't looked into. I still have very much to learn about it, so some things are not obvious for me yet. Thank you again form being so available. Ciao

Happy to help! Kubernetes is a huge topic, you literally never finish learning this stuff!

**Comment by vinnytwice** [comment]
It's huge topic indeed! Luckily I love being always learning new stuff. 
Thanks again. Cheers

**Comment by jampy** [comment]
@vinnytwice I'm also in the process of learning. Am I right that hetzner-k3s does not support NetworkPolicies out of the box and special configuration is needed (as discussed here)?

Thanks

**Comment by vitobotta** [comment]
@jampy I haven't tried them but k3s supports network policies via kube-router https://www.suse.com/c/rancher_blog/k3s-network-policy/
