### ISSUE TITLE
K3s versions

### ISSUE THREAD

**Issue by AnttiKarvinen** [vitobotta/hetzner-k3s#266]
I'm wondering about what version k3s to use, we have used your tool to make cluster with v1.26.1+k3s1 but i updated servers to v1.26.7+k3s1. 
Our autoscale clusters are still coming up with v1.26.1+k3s1 and  your tools command `hetzner-k3s releases` gives the latest as v1.26.1+k3s1, but your `cluster_config.yaml.example` is marked as v1.26.4+k3s1.

Would it be possible to bypass the k3s_version check in  `cluster_config` so that i could make some arrangements to our cluster?

And thank you for very good tool!

**Comment by vitobotta** [comment]
Did you perform the upgrade as described in the README?

If the `releases` command doesn't return latest versions delete the file k3s-releases.yaml from your tmp folder. The tool caches the list there since there are some strict limits for unauthenticated API calls with Github.

**Comment by vitobotta** [comment]
ole hyvä :)

Will add a note to the README about it :)

**Comment by vitobotta** [comment]
I guess we can close this?

**Comment by AnttiKarvinen** [comment]
Please close this, thank you still!
