### ISSUE TITLE
change in Hetzner API - 1 OCT 2023

### ISSUE THREAD

**Issue by psavva** [vitobotta/hetzner-k3s#268]
Dear @vitobotta 

Please be aware of the API change.
https://status.hetzner.com/incident/21307528-ede6-4a43-8641-3fdd6fbb03fe

Please feel free to close this issue if there is no impact due to this change.

**Comment by vitobotta** [comment]
Hi, thanks for sharing. It doesn't seem to affect us from what I can see so I'll close this for now.
