### ISSUE TITLE
Why do the hetzner worker nodes have public ips exposed ? Is there a way to only allow private ips for hetzner nodes ?

### ISSUE THREAD

**Issue by easyStartup-pulse** [vitobotta/hetzner-k3s#273]
For safety and security purposes I do not want my nodes to be accessible from outside, they should only be accessible via a load balancer. Could you please suggest a way for me to do so via automation using config ? 

I have a lot of attached network volume and i dont want my nodes accessible from outside the cluster/private network unless there a external ingress load balancer setup. Please help on how to achieve this and as a configurable behaviour in the cluster_config.yaml.

P.S. I absolutely love ❤️ this product makes it very very simple to provision nodes (arm and amd64) and adds all the required setup in an instant. Please keep up the good work.

**Comment by derlinuxer** [comment]
it is that what you are looking for?
https://github.com/vitobotta/hetzner-k3s/discussions/252

**Comment by easyStartup-pulse** [comment]
yes let me explore it further. Thank you. I’ll have to compile locally. Is it possible to add it as a general availability

**Comment by derlinuxer** [comment]
> yes let me explore it further. Thank you. I’ll have to compile locally. Is it possible to add it as a general availability

chrck my fork https://github.com/derlinuxer/hetzner-k3s
I'll try to hold this in sync as long as the PR at the main project isn't merged. We use it in production since 3 Months.

**Comment by vitobotta** [comment]
I released v1.1.4 with the awesome contribution by @derlinuxer :)

Closing this one but feel free to reopen if you have problems with the new release.
