### ISSUE TITLE
Stuck on "Waiting for successful ssh connectivity with server cloudie-cax11-master3..."

### ISSUE THREAD

**Issue by Danielss89** [vitobotta/hetzner-k3s#290]
Hi

I am trying to set up a cluster, but it seems like it gets stuck on the ssh connection to server 3.
```
hetzner-k3s create --config cluster_config.yaml
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Network already exists, skipping.
Updating firewall...done.
SSH key already exists, skipping.
Placement group cloudie-masters already exists, skipping.
Server cloudie-cax11-master1 already exists, skipping.
Server cloudie-cax11-master2 already exists, skipping.
Server cloudie-cax11-master3 already exists, skipping.
Server cloudie-cax11-master1 already exists, skipping.
Waiting for successful ssh connectivity with server cloudie-cax11-master1...
Server cloudie-cax11-master2 already exists, skipping.
Waiting for successful ssh connectivity with server cloudie-cax11-master2...
Server cloudie-cax11-master3 already exists, skipping.
Waiting for successful ssh connectivity with server cloudie-cax11-master3...
```

It has been like that for ~30 minutes now.
I've tried deleting the server and, it creates a new one, but same problem

**Comment by vitobotta** [comment]
Hi, what kind of SSH key are you using? Does it have a passphrase?

**Comment by Danielss89** [comment]
No, there is no passphrase.
Another note: I can manually ssh into the servers succesfully

**Comment by Danielss89** [comment]
My mistake. The ssh key actually is password protected!
Do i need to create one without passphrase?

**Comment by Danielss89** [comment]
I removed the passphrase from the key, and it now works :)
Would be cool if it could work with passphrase though.

**Comment by vitobotta** [comment]
You can also keep the passphrase and enable the agent in the yaml config :)
