### ISSUE TITLE
Disabling kube-proxy configuration

### ISSUE THREAD

**Issue by georgeVasiliu** [vitobotta/hetzner-k3s#302]
Hello,

In the same idea that if we want to use another CNI than flannel we have the disable-flannel flag, I think it would be useful to also introduce a new flag called disable-proxy, which would simply add in the scripts the --disable-kube-proxy argument for k3s when installing it.

This is necessary for example in case of using Cilium + Gateway API, in which you are forced to use Cilium as a kubeProxy replacement completely and it requires the underlying cluster to not have kubeProxy enabled: https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/

Would it be possible to add such support for that flag and when it's detected to add the necessary argument in the k3s installer script?

Thanks for this library also!

**Comment by georgeVasiliu** [comment]
Updated: I forked the repository and opened a new branch in the fork, I only have found 2 places which needed changes:


![image](https://github.com/vitobotta/hetzner-k3s/assets/26601265/15465a58-6ff3-4020-a71e-f5bbf63809b1)

I just looked into it out of curiosity of how much work it would be needed to add this flag. If you want, I can open a pull request with those changes?

**Comment by vitobotta** [comment]
Hi! A PR would be lovely, thanks :)

**Comment by georgeVasiliu** [comment]
Hi! I opened the pull request and added one note I had over there. Hope I didn't overlook anything. I'll have a final check this evening to make sure there wasn't anything else that needed to be adjusted.

**Comment by vitobotta** [comment]
Hi, like I mentioned in the PR the kube proxy is disabled when you disable flannel. Let's continue the discussion in the PR anyway.
