### ISSUE TITLE
Disabling Flannel results in connectivity problems (pods, nodes, deployments)

### ISSUE THREAD

**Issue by x86fantini** [vitobotta/hetzner-k3s#305]
Hello Vito, thank you for you excelent work.
I am using as a playground your script and it works like a charm. I would like to disable flannel, as per the config line

`disable_flannel: true # set to true if you want to install a different CNI`

but i did not find any documentation on this, so i have tried 3/4 times and results are alwasy the same: the script finishes to create the workers but from lens i can see that pods (calico, dns, etc) fails to start and to comunicate with each others

i have tried many combos (different datacenter, different types of VM) but no luck.

1. i am using Ubuntu 22.04 as default image
2. i am using stable k3s version `v1.28.5+k3s1`

my goal is to build the cluster succesfully then install Cilium as CNI.

thank you

**Comment by x86fantini** [comment]
hi @vitobotta at the end it was correct: just create the cluster with "disable_flannel" set to true and even if there are many failed pods or exception, just hang tight. I have installed Calico CNI and after installation pods restarted and connectivity was back to normal.

So ye, who wants to swap flannel for other CNI, just don't look at the connectivity issues as soon cluster comes up, but just procede with CNI installation

**Comment by vitobotta** [comment]
Hi, glad you got it sorted. Sorry for the late reply but I am quite busy with work at the moment.
