### ISSUE TITLE
If node as IP ending with 1, lo is selected as flannel interface

### ISSUE THREAD

**Issue by cwilhelm** [vitobotta/hetzner-k3s#313]
I have `private_network_subnet: 10.1.0.0/16` and a host with IP **10.1.0.1** then
`private_network_test_ip: settings.private_network_subnet.split(".")[0..2].join(".") + ".1"` evaluates to **10.1.0.1** and `NETWORK_INTERFACE=$(ip route get {{ private_network_test_ip }} | awk -F"dev " 'NR==1{split($2,a," ");print a[1]}')`
 evaluates to **lo** which should be for example **ens10**.

This leads to a setting of `--flannel-iface=lo` and a failing flannel service.

Fix would be to `private_network_test_ip: settings.private_network_subnet.split(".")[0..2].join(".") + ".1"`

**Comment by vitobotta** [comment]
Hi, and sorry for the delay. Since you identified both the problem and a fix already would you be willing to open a PR for it?

**Comment by cwilhelm** [comment]
https://github.com/vitobotta/hetzner-k3s/pull/315

**Comment by vitobotta** [comment]
The PR has been merge, thanks again!
