### ISSUE TITLE
Allow to customize use used image

### ISSUE THREAD

**Issue by robjuz** [vitobotta/hetzner-k3s#33]
It would be nice to be able to use custom image. E.x a Snapshot 

I installed longhorn on me Cluster and wanted to use a RWX PVC. NFS Support Must be installed in the system. I would like to install it once, create a snapshot and use it as base for the nodes.

**Comment by vitobotta** [comment]
It should be possible. I'll have a look if I can implement this in the weekend.

**Comment by vitobotta** [comment]
Done in 0.4.7 (latest). You can now use a custom snapshot but in that case you'll need to specify the **ID** of the snapshot, not the description. See README for details. Also using a custom image makes the creation slower. I'm closing - feel free to reopen if you have problems with this.

**Comment by robjuz** [comment]
❤️
