### ISSUE TITLE
Configure worker nodes to use floating IPs

### ISSUE THREAD

**Issue by dclayton77** [vitobotta/hetzner-k3s#331]
During cluster creation, is it possible to configure Hetzner to use Floating IP addresses for nodes? The reason is I use whitelisting of the
node IP address for access to Azure services, Kong Whitelisting etc. For now, I have the IP hardcoded but when it changes, I need to update and redeploy several services. If I could use a Floating IP, I believe that I could use that for whitelisting a node and then it would not matter if the actual IP address changes.

Ideally this would be done as part of the YAML configuration as I am trying to avoid any manual intervention.

**Comment by vitobotta** [comment]
This would add a huge amount of complexity for a very specific use case, so I am not gonna implement it, sorry. Why can't you just use a proxy and whitelist the proxy IP?

**Comment by dclayton77** [comment]
Thanks for coming back to me.  I hadn't realised that this would be quite complex so understand that you won't implement it.  I will look into using a proxy instead.
