### ISSUE TITLE
Hanging on ssh connectivity with server

### ISSUE THREAD

**Issue by sujeeruban** [vitobotta/hetzner-k3s#364]
Hi, I tried to set up a k3s cluster with **disabled external interfaces** but encountered the following error. There are no firewall blocks.  could you please help me on this?

- passphrase on the ssh key
- use_ssh_agent to true

Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Creating firewall...done.
Creating SSH key...done.
Creating placement group rge-test-masters...done.
Placement group rge-test-arm-1 already exists, skipping.
Creating server rge-test-cax11-pool-arm-worker2...
Creating server rge-test-cax11-master1...
Creating server rge-test-cax11-pool-arm-worker1...
...server rge-test-cax11-pool-arm-worker1 created.
...server rge-test-cax11-pool-arm-worker2 created.
...server rge-test-cax11-master1 created.
Server rge-test-cax11-master1 already exists, skipping.
Waiting for successful ssh connectivity with server rge-test-cax11-master1...
Server rge-test-cax11-pool-arm-worker1 already exists, skipping.
Waiting for successful ssh connectivity with server rge-test-cax11-pool-arm-worker1...
Server rge-test-cax11-pool-arm-worker2 already exists, skipping.
Waiting for successful ssh connectivity with server rge-test-cax11-pool-arm-worker2...

Did I miss something?
-----------------------------------------------------
hetzner_token: ""
cluster_name: rge-test
kubeconfig_path: "./kubeconfig"
k3s_version: v1.26.5+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
use_ssh_agent: true
ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0
schedule_workloads_on_masters: false
private_network_subnet: 10.2.0.0/16
existing_network: net-kube-test
enable_public_net_ipv4: false
enable_public_net_ipv6: false
disable_flannel: false
cloud_controller_manager_manifest_url: "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.16.0/ccm-networks.yaml"
system_upgrade_controller_manifest_url: "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
csi_driver_manifest_url: "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.3.2/deploy/kubernetes/hcloud-csi.yml"
masters_pool:
  instance_type: cax11
  instance_count: 1
  location: fsn1
  image: 103908130
worker_node_pools:
- name: arm
  instance_type: cax11
  instance_count: 2
  location: fsn1
  image: 103908130
post_create_commands:
  - timedatectl set-timezone Europe/Berlin
  - >
    printf "network## {config## disabled}" |
    sed 's/##/:/g' > /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
  - >
    printf "network##\n  version## 2\n  renderer## networkd\n  ethernets##\n    enp7s0##\n      dhcp4## true\n      nameservers##\n        addresses## [185.12.64.1, 185.12.64.2]\n      routes##\n        - to## default\n          via## 10.2.0.1" |
    sed 's/##/:/g' > /etc/netplan/50-cloud-init.yaml
  - netplan generate
  - netplan apply
  - apt update
  ---------------------------------------------------------------------------------

**Comment by ajaysourcedigital** [comment]
same issue with me.

**Comment by vitobotta** [comment]
Hi, rc1 of v2 is now available and includes some changes that should help with these issues. Would you be able to help with testing? if yes see https://github.com/vitobotta/hetzner-k3s/discussions/385 for details. Thanks

**Comment by vitobotta** [comment]
v2 is going to be released next weekend with lots of improvements that address various reasons for hanging. So I am closing this - please open a separate issue if you can still reproduce this kind of issue with v2. Thanks!
