### ISSUE TITLE
Cluster Auto Scaler not deploying due to invalid image

### ISSUE THREAD

**Issue by psavva** [vitobotta/hetzner-k3s#365]
Dear @vitobotta 

Please see the issue linked and PR opened on the autoscaler specifically for the cluster autoscaler
https://github.com/kubernetes/autoscaler/pull/6851

Once this is fixed, please go ahead and close this issue

**Comment by vitobotta** [comment]
Thanks for the heads up! I am going to work more on the project in the weekend and I will keep this in mind. Thanks

**Comment by apricote** [comment]
Hey @psavva ,

What error do you see when running cluster-autoscaler? I know of a few errors in 1.28-1.30 that will be fixed in the next patch releases, but there might still be something I have not encountered so far.

**Comment by vitobotta** [comment]
I had forgotten to update this issue but there have been many updates to the autoscaler stuff since then and v2 is going to be released soon, probably next weekend, so I am closing this now.
