### ISSUE TITLE
Cluster initialization post initialization commands.

### ISSUE THREAD

**Issue by DeprecatedLuke** [vitobotta/hetzner-k3s#367]
It would be great if there was a way to run post-install kubectl commands using the generated kubeconfig. Currently it can be performed with an external script so the priority for this is low.

Although it would be nice if it was possible to have a configuration option:
```
post_initialization_kubectl_commands:
- create -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/tigera-operator.yaml
```

This would streamline any kind of post-initialization logic for the cluster itself rather than any particular node.

I would be happy to create a pull request for this if this is something that sounds like a good idea and others are interested in it.

**Comment by vitobotta** [comment]
Sorry for the delay, it looks like I missed some issues at a time I was super busy with work.

This is actually a lovely idea! If you can make a PR that would be welcome, otherwise I will implement it myself in 2.0.1 or 2.0.2. v2 is going to be released soon, probably next weekend.

**Comment by DeprecatedLuke** [comment]
I swapped to mostly bash based installer so not really interested anymore considering it's a language I don't really know and there's several other problems such as determining when a cluster is ready to accept deployments since nodes will not be come ready until a CNI is present if default is disabled.

**Comment by vitobotta** [comment]
Thanks for letting me know.
