### ISSUE TITLE
rancher/system-upgrade-controller:latest doesn't exist

### ISSUE THREAD

**Issue by MuhanedYahya** [vitobotta/hetzner-k3s#370]
Pod Logs:
```
  Normal   Pulling           23m (x4 over 24m)     kubelet            Pulling image "rancher/system-upgrade-controller:latest"
  Warning  Failed            23m (x4 over 24m)     kubelet            Failed to pull image "rancher/system-upgrade-controller:latest": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/system-upgrade-controller:latest": failed to resolve reference "docker.io/rancher/system-upgrade-controller:latest": docker.io/rancher/system-upgrade-controller:latest: not found
```

**Comment by khustochka** [comment]
This is a rancher issue: https://github.com/rancher/system-upgrade-controller/issues/302

**Comment by jerve** [comment]
I guess this could be worked around by defining the system_upgrade_controller_crd_manifest_url in the settings pointing to a tag that is not "latest" anyway, as this is considered bad practice.

**Comment by creib** [comment]
Adding these two lines did not fix it for me
```
system_upgrade_controller_deployment_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml"
```
Do I miss something?

**Comment by vitobotta** [comment]
> Adding these two lines did not fix it for me
> 
> ```
> system_upgrade_controller_deployment_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
> system_upgrade_controller_crd_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/crd.yaml"
> ```
> 
> Do I miss something?

These are the versions I am using with v2 under development and they seem to be working fine for me. Do the images get pulled or not at all?

**Comment by creib** [comment]
When adding the lines to the config and running hetzner-k3s create, the system-upgrade-controller gets again deployed with the latest version. If I change it in the deployment to v0.13.4 it gets pulled and it is running.
I am using version 1.1.5.

**Comment by vitobotta** [comment]
> When adding the lines to the config and running hetzner-k3s create, the system-upgrade-controller gets again deployed with the latest version. If I change it in the deployment to v0.13.4 it gets pulled and it is running. I am using version 1.1.5.

Oh, this is my bad, sorry. The actual name of the setting in the current stable version is `system_upgrade_controller_manifest_url`; by mistake I recently merged the WIP branch for v2 into main, so I can see that this can cause confusion when reading the README. 

Please try the `system_upgrade_controller_manifest_url` setting instead. I'll see if I can revert the README in main if I cannot finalize v2 soon enough. Sorry for the confusion.

**Comment by creib** [comment]
`system_upgrade_controller_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"
`
Works also perfect, thank again!

**Comment by vitobotta** [comment]
> `system_upgrade_controller_manifest_url: "https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml" ` Works also perfect, thank again!

Cool, sorry again for the confusion :)

**Comment by vitobotta** [comment]
Closing since improvements have been made in v2, which is going to be released probably this weekend or anyway pretty soon.
