### ISSUE TITLE
Simple test cluster stuck in assigning `core-dns`

### ISSUE THREAD

**Issue by pat-s** [vitobotta/hetzner-k3s#376]
Pretty much using the default config with the following changes

```yml
k3s_version: v1.29.6+k3s1

masters_pool:
  instance_type: cpx11
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: small-static
  instance_type: cpx11
  instance_count: 1
  location: fsn1
```

When applying, the tool gets stuck at

```
[INFO]  Creating uninstall script /usr/local/bin/k3s-agent-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s-agent.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s-agent.service
[INFO]  systemd: Enabling k3s-agent unit
[INFO]  systemd: Starting k3s-agent
```

Inspecting the cluster, I see 

```
Warning  FailedScheduling  5m6s  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.cloudprovider.kubernetes.io/uninitialized: true}. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling
```

Applied via v1.1.5 on macOS.

**Comment by vitobotta** [comment]
Hi, you don't see any errors? Have you tried re-running the create command?

**Comment by pat-s** [comment]
Jup retried everything and also deleted the cluster and re-applied again. 

The only issue I see is that core-dns can't even be assigned due to the taint issue mentioned. 

Everything else is the the same to your README config.

**Comment by vitobotta** [comment]
And you don't see any errors printed by the create command? What OS are you on and can you share the full config file minus the token?

**Comment by pat-s** [comment]
No, there were no errors, the command just didn't finish.

I've created an entirely new project and tried again, it worked fine then. Not sure what the reason was, the initial project was also empty as I just opened the account and never deployed anything.

Thanks for the quick reply and help, keep it going, great project!
