### ISSUE TITLE
cluster_config.yaml.example - needs update

### ISSUE THREAD

**Issue by talkyoo** [vitobotta/hetzner-k3s#38]
I copied the cluster_config.yaml.example to my personal k3s-hetzner.yaml

it took me some time to figured out, that  

* ssh_key_path is now public_ssh_key_path
* private_ssh_key_path is missing
* ssh_allowed_network is missing 

create_cluster.yaml.example is != of readme section "Creating a cluster".

**Comment by vitobotta** [comment]
Which yaml are you referring to? I just checked if I updated the [README](https://github.com/vitobotta/hetzner-k3s#creating-a-cluster) and it seems that I did. So I am not sure of which section you mean.

**Comment by vitobotta** [comment]
Oh I see, I forgot to update that file. Sorry :)

**Comment by vitobotta** [comment]
Thanks for reporting this, I have updated the cluster.yaml.example file.
