### ISSUE TITLE
Unable to deploy Hetzner drivers

### ISSUE THREAD

**Issue by creib** [vitobotta/hetzner-k3s#382]
Hi,

I am trying to upgrade my three master nodes to cx22 nodetypes and I always get the following error:

```
=== Deploying Hetzner drivers ===

Creating secret for Hetzner Cloud token...
Unable to connect to the server: tls: failed to verify certificate: x509: certificate signed by unknown authority
Failed to create Hetzner Cloud secret:
#<Util::Shell::Result:0x103307880>
```

Any idea what might be the root cause? When I go back to the existing nodes cx11 the script runs fine again...

Best

**Comment by vitobotta** [comment]
How did you upgrade the master nodes? Did you just change the instance type in the config file and re-run the create command? If yes that won't work unfortunately as inplace upgrades are not supported. What you can do is just leave the instance type as it was in the config file and upgrade the instances from the Hetzner Console. As long as the names of the instances don't change, everything should still work normally. In v2, which is currently under development, I am removing the instance type from the names of instances so to avoid confusion when the instances are rescaled from the Hetzner console as suggested above, but this won't apply to existing clusters for obvious reasons.

**Comment by creib** [comment]
This sounds reasonable. So I will upgrade the Nodes using the Hetzner Console. If I apply the configuration afterwards, will it still work or do I have to upgrade the instance types in the configuration as well?

**Comment by creib** [comment]
This worked perfect, thanks a lot for your support!

**Comment by vitobotta** [comment]
> This worked perfect, thanks a lot for your support!

Nice, glad it helped :)

It would be super awesome if it were possible to easily rename nodes in Kubernetes, so I could implement an automatic migration in the tool to remove the instance type from the instance names, but AFAIK it's not possible unfortunately. But as long as you leave the instance type unchanged in the config file, and don't change the names of the instances manually, you can scale instances up and down as you please :)

**Comment by wflanagan** [comment]
When your node type is no longer supported, you deploy and get into a mess. I wish i'd have seen this before i started the upgrade.
