### ISSUE TITLE
macOS x86 release seems to be an arm binary (v2.0.0+)

### ISSUE THREAD

**Issue by cmantsch** [vitobotta/hetzner-k3s#414]
The published binary for macOS x86 (both GitHub and also over Homebrew) seems to be a arm binary.

Trying to run it returns the following error:
```
$ hetzner-k3s
zsh: bad CPU type in executable: hetzner-k3s
```

Getting the file information confirms it is an arm binary:
```
$ file hetzner-k3s-macos-amd64
hetzner-k3s-macos-amd64: Mach-O 64-bit executable arm64
```

This seems to be an issue since 2.0.0, the previous release 1.1.5 correctly is identified as x86_64. Maybe a misconfiguration in the build pipeline?

**Comment by vitobotta** [comment]
Hi, thanks for reporting this. I only have an ARM mac so I hadn't noticed. I will look into is as soon as I can but I am handling a support case at work at the moment so it will be a bit later.

**Comment by vitobotta** [comment]
It looks like Github Actions changed the version of macos for the Intel macs, so I made this change and am releasing a temp 2.0.2.rc1 version to see if it's fixed. I'll ping you when ready so you can double check :)

**Comment by vitobotta** [comment]
Can you try the new binary from https://github.com/vitobotta/hetzner-k3s/releases/tag/v2.0.2.rc1?

**Comment by cmantsch** [comment]
Thanks for the quick response, the 2.0.2.rc1 works fine again, thank you very much!
```
$ file hetzner-k3s-macos-amd64
hetzner-k3s-macos-amd64: Mach-O 64-bit executable x86_64
```

**Comment by vitobotta** [comment]
Thanks for confirming! I will release 2.0.2 now. Sorry for the trouble but like I said I don't own an Intel mac at the moment so I hadn't noticed that change with the OS images for GA. Closing this since it seems resolved. Check for the 2.0.2 release in a bit :)

**Comment by cmantsch** [comment]
No worries, can happen to everyone :)

I have to thank for the quick resolve :D
