### ISSUE TITLE
hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:279:in `deploy_kubernetes': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ZaDarkSide** [vitobotta/hetzner-k3s#42]
I seem to have an issue with this ruby gem:

```
hetzner-k3s create-cluster --config-file cluster_config.yaml

Placement group already exists, skipping.


Creating firewall...
...firewall created.


Creating private network...
...private network created.


SSH key already exists, skipping.




Creating server kubernetes-cx11-pool-small-worker1...
Creating server kubernetes-cx21-pool-big-worker1...
Creating server kubernetes-cpx31-master1...
...server kubernetes-cx21-pool-big-worker1 created.

...server kubernetes-cx11-pool-small-worker1 created.

...server kubernetes-cpx31-master1 created.


Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
Waiting for server kubernetes-cpx31-master1 to be up...
Waiting for server kubernetes-cx21-pool-big-worker1 to be up...
Waiting for server kubernetes-cx21-pool-big-worker1 to be up...
Waiting for server kubernetes-cpx31-master1 to be up...
Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
Waiting for server kubernetes-cx21-pool-big-worker1 to be up...
Waiting for server kubernetes-cpx31-master1 to be up...
Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
Waiting for server kubernetes-cx21-pool-big-worker1 to be up...
Waiting for server kubernetes-cpx31-master1 to be up...
Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
Waiting for server kubernetes-cx21-pool-big-worker1 to be up...
Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
Waiting for server kubernetes-cpx31-master1 to be up...
Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
Waiting for server kubernetes-cpx31-master1 to be up...
Waiting for server kubernetes-cx21-pool-big-worker1 to be up...
...server kubernetes-cx21-pool-big-worker1 is now up.
...server kubernetes-cpx31-master1 is now up.
Waiting for server kubernetes-cx11-pool-small-worker1 to be up...
...server kubernetes-cx11-pool-small-worker1 is now up.

Traceback (most recent call last):
        9: from /root/.rbenv/versions/2.7.4/bin/hetzner-k3s:23:in `<main>'
        8: from /root/.rbenv/versions/2.7.4/bin/hetzner-k3s:23:in `load'
        7: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/exe/hetzner-k3s:4:in `<top (required)>'
        6: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        5: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        4: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        3: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        2: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cli.rb:28:in `create_cluster'
        1: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:42:in `create'
/root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:279:in `deploy_kubernetes': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by ZaDarkSide** [comment]
Basically this happens because `find_server(server_name)` fails it doesn't takes into account pagination from the api.

**Comment by ZaDarkSide** [comment]
I've added a hackfix so that the target servers show up in first request on page 1 with sorting by newest created severs in `"/root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/infra/server.rb"` line `75`:

```
      def find_server(server_name)       
        hetzner_client.get("/servers?sort=created:desc")["servers"].detect{ |network| network["name"] == server_name }
      end
```

**Comment by ZaDarkSide** [comment]
The new error I get now is:

```
Traceback (most recent call last):
        9: from /root/.rbenv/versions/2.7.4/bin/hetzner-k3s:23:in `<main>'
        8: from /root/.rbenv/versions/2.7.4/bin/hetzner-k3s:23:in `load'
        7: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/exe/hetzner-k3s:4:in `<top (required)>'
        6: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        5: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        4: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        3: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        2: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cli.rb:28:in `create_cluster'
        1: from /root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:44:in `create'
/root/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:283:in `deploy_kubernetes': undefined method `[]' for nil:NilClass (NoMethodError)
```

Probably same cause but different source

**Comment by ZaDarkSide** [comment]
Okay the hackfixes worked for me, but the API handling must be rewritten to take into account the pagination because not all the needed data is returned from Hetzner in a single request.

**Comment by vitobotta** [comment]
I'll take a look at implementing pagination when I have a bit more time. But I wouldn't keep many servers, especially if unrelated, in the same project. I prefer to keep things in separate projects depending on what they do. The Ruby gem creates resources with names that depend on the name of the cluster and of the node pools, so when you delete the cluster it will delete resources which match that convention. So it should be safe but I still recommend keeping things separate.

**Comment by ZaDarkSide** [comment]
> I'll take a look at implementing pagination when I have a bit more time. But I wouldn't keep many servers, especially if unrelated, in the same project. I prefer to keep things in separate projects depending on what they do. The Ruby gem creates resources with names that depend on the name of the cluster and of the node pools, so when you delete the cluster it will delete resources which match that convention. So it should be safe but I still recommend keeping things separate.

Suggestion duly noted, thanks and keep up the good job!

**Comment by niclash** [comment]
Similar thing is happening at
```
/var/lib/gems/2.7.0/gems/hetzner-k3s-0.4.8/lib/hetzner/k3s/cluster.rb:461
```

The `server` parameter is nil/null/empty (whatever it is called in Ruby) sometimes, and it would fit with the pagination issue.

**Comment by vitobotta** [comment]
> > I'll take a look at implementing pagination when I have a bit more time. But I wouldn't keep many servers, especially if unrelated, in the same project. I prefer to keep things in separate projects depending on what they do. The Ruby gem creates resources with names that depend on the name of the cluster and of the node pools, so when you delete the cluster it will delete resources which match that convention. So it should be safe but I still recommend keeping things separate.
> 
> Suggestion duly noted, thanks and keep up the good job!

For the time being I have just added your hack to have the latest servers in the first page of the API response, since I think it's 50 servers per page so the problem would occur now with very large clusters. I will do some more work with the pagination if people keep having this problem  but so far it has occurred only to you. Thanks for the suggestion on sorting the servers by creation page. I'm closing this for now but if I end up implementing the pagination I will update this.
