### ISSUE TITLE
is downgrade k3s possible?

### ISSUE THREAD

**Issue by jboesh** [vitobotta/hetzner-k3s#43]
Hi!
a quick question because the readme only describes the k3s upgrade process. Is downgrade also possible?
the reason why Iam asking is, I have the 1.22.3 + k3s1 version but Rancher requires < 1.22.0-0

`PS C:\kluster> helm upgrade --install --namespace cattle-system --set hostname=rancher.mydomain.com --set ingress.tls.source=letsEncrypt --set letsEncrypt.email=myemail@gmail.com rancher rancher-stable/rancher`

```
Release "rancher" does not exist. Installing it now.
helm : Error: chart requires kubeVersion: < 1.22.0-0 which is incompatible with Kubernetes v1.22.3+k3s1
At line:1 char:1
+ helm upgrade --install --namespace cattle-system --set hostname=ranch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: chart re...es v1.22.3+k3s1:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by vitobotta** [comment]
I have never tried downgrading but it may work. At least it works if you install k3s withe official bash script directly and run it again with a lower version. So it may work with the upgrade controller too, not sure. I suggest you create another test cluster in a separate Hetzner project with 1.22.3, then try to "upgrade" specifying 1.22.0. Let me know how it goes, I'm curious.

**Comment by jboesh** [comment]
because I have some thing running already and configured, I will try this later. but thanks for the reply, i will come back with an answer

**Comment by vitobotta** [comment]
OK, closing for now.

**Comment by ramzcode** [comment]
@jboesh BTW did you try to downgrade, did it work? Please let me know.

**Comment by jboesh** [comment]
I tried but got some crazy errors (unfortunately couldn't capture them), that didn't give me confidence to continue.
I then did a fresh install
