### ISSUE TITLE
How to update k3s releases?

### ISSUE THREAD

**Issue by jampy** [vitobotta/hetzner-k3s#439]
The [docs](https://github.com/vitobotta/hetzner-k3s/blob/cc73a0aaf303c1280228bbc57a22f85490a5c4de/docs/Creating_a_cluster.md) mention `k3s_version: v1.30.3+k3s1` and [other people](https://github.com/vitobotta/hetzner-k3s/issues/397) seem to use that release just fine. However, that release is not available to me.

Is the releases list stored in some configuration file? I thought it is hardcoded into the `hetzner-k3s` binary.

```
# hetzner-k3s --version
2.0.8

# hetzner-k3s releases | sort | tail
v1.27.5-rc2+k3s1
v1.27.5-rc3+k3s1
v1.27.6+k3s1
v1.27.6-rc1+k3s1
v1.28.0-rc1+k3s1
v1.28.1+k3s1
v1.28.1-rc1+k3s1
v1.28.1-rc2+k3s1
v1.28.2+k3s1
v1.28.2-rc1+k3s1
```

Also when trying to `hetzner-k3s create` with `k3s_version: v1.30.3+k3s1` I get this error (unsurprisingly):

```
[Configuration] Validating configuration...
[Configuration] Some information in the configuration file requires your attention:
[Configuration]  - K3s version is not valid, run `hetzner-k3s releases` to see available versions
```

**Comment by vitobotta** [comment]
Release list is cached to workaround the rate limits with authenticated API calls on Github. To refresh the list just delete /tmp/k3s-releases.yaml and re-run the command again. :)

**Comment by vitobotta** [comment]
I have implemented an update that will automatically refresh the list if the cached version is more than 7 days old. This adjustment will be included in the upcoming release, aiming to prevent such confusion in the future. :)
