### ISSUE TITLE
Creating infrastructure resources  -  400 Bad Request

### ISSUE THREAD

**Issue by od081274gil** [vitobotta/hetzner-k3s#464]
I have message, how it fix ?
Validating configuration......configuration seems valid.

=== Creating infrastructure resources ===
Failed to create network: HTTP status code 400: Bad Request
{
    "error": {
        "code": "json_error",
        "message": "A valid JSON document is required."
    }
}

**Comment by vitobotta** [comment]
Which version of hetzner-k3s are you using?

**Comment by od081274gil** [comment]
Thank you
