### ISSUE TITLE
username and password to access the server (for the volume). I need to edit a file in a volume

### ISSUE THREAD

**Issue by jboesh** [vitobotta/hetzner-k3s#47]
Hi!

I need to edit some values in a config file, which is saved on a volume (On a specific Hetzner cloud server)
what is the way to do this? 
When I logon to Hetzner cloud, volumes and click on the cloud server and 'Console', it is asking for an username and password.
These are not the Hetzner cloud credentails.
![image](https://user-images.githubusercontent.com/71582854/145378059-d283e3ce-48d8-4c28-88e7-0abd29513ccf.png)

a reply from their support
```
As mentioned the login for a cloud server is always "root".

If you created the ssh key after creating the server it is not deposited on the remote system. This means you have to reset the password of your server.

If you have created the server and selected the ssh key during initial setup you can login without a password.
```
does your script generate the ssh key before or after the creating of the server?
anyway, when I try some combinations (username Root and or without password), none of them works

What am I doing wrong?

Can I reset the password without any problems? the server should just keep working from the cluster

**Comment by vitobotta** [comment]
Hi, when you create a cluster you specify your public SSH key in the config file for the cluster. You can use the corresponding private key with the root user to SSH into the instances. The installer doesn't create a new SSH key, it just uses what you specify. You shouldn't need the password. Try with

```bash
ssh -i <path of private key> root@<ip address>
```

**Comment by vitobotta** [comment]
But, after re-reading, I am not sure of what you are trying to do exactly. Can you clarify?

**Comment by jboesh** [comment]
Ive applied a nextcloud deployment and it is using the hetzner storage class to put application files on a hetzner volume for persistent storage.
I need to edit a file on the volume
But i dont know how to do that the quickest way

**Comment by vitobotta** [comment]
Is the volume attached and mounted to a pod? If yes you can just exec into the pod to access the volume. If it's not attached to a pod you could run a temporary pod with Ubuntu image or something and mount the volume there.

**Comment by jboesh** [comment]
Hi. Yes the volume is in use by the pod.
I can use the exec command to put files on the volume but not view the file right? On my notepad for instance
So i need to view a file put a some lines in it and save it agian
Thats not possible with exec i thought

**Comment by vitobotta** [comment]
It depends on the image used for the container in the pod. If it's running as root you may be able to install and run vim or something and edit the file that way.

**Comment by jboesh** [comment]
thanks Vito!
