### ISSUE TITLE
Unable to install via brew, openssl@1.1 disabled

### ISSUE THREAD

**Issue by creib** [vitobotta/hetzner-k3s#476]
After setting up my new mac laptop I face the following problem. When trying to install hetzner-k3s via brew:

`brew install  vitobotta/tap/hetzner_k3s`

I get the following errormessage:

`Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.`

**Comment by vitobotta** [comment]
Thanks for reporting it. I didn't know openssl 1.1 had been deprecating. Can you use the binary instead for the time being and install the required dependencies with homebrew manually for now?

**Comment by vitobotta** [comment]
Hi, I have updated the formula so it no longer depends on openssl 1.1. Let me know if you still have some issues with this.

**Comment by creib** [comment]
I just gave it a try, works perfect. Thanks a lot!

**Comment by vitobotta** [comment]
Awesome. I'll close this then.
