### ISSUE TITLE
New Master not added to Cluster

### ISSUE THREAD

**Issue by ramzcode** [vitobotta/hetzner-k3s#49]
Hi

Deleted my problematic Master node and reran create-cluster CLI but the node was created as a standalone K3s node. 

kubeclt get nodes -- lists only the new master.

**Comment by vitobotta** [comment]
You cannot replace the master in an existing cluster. That will create a new cluster. What you can do is for example increase from one to multiple masters, but recreating the master means losing the state of the previous cluster so it won't work.
