### ISSUE TITLE
Kubeconfig randomly stopped working

### ISSUE THREAD

**Issue by emrys90** [vitobotta/hetzner-k3s#492]
It used to work, but it randomly started giving these errors.
E1128 08:39:59.987712   43556 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials

If I ssh into the master node, kubectl commands correctly run there. So kubernetes is working. Any ideas how to fix this?

**Comment by vitobotta** [comment]
Glad you managed to figure it out. For next time, if you have a similar question, it's a good idea to start a Discussion instead of an Issue. Discussions are better suited for these kinds of questions :)
