### ISSUE TITLE
Feature Idea: Autoscaling?

### ISSUE THREAD

**Issue by flobaader** [vitobotta/hetzner-k3s#51]
Hello @vitobotta,

thanks a lot for the nice project! I was wondering if it would be possible to enable autoscaling for specific nodepools. I think that would be the last missing feature for a fully fledged Kubernetes hosting.

I found this project here, but I'm not sure if this can be integrated.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/hetzner/README.md

Best whishes,
Florian Baader

**Comment by vitobotta** [comment]
Hi Florian, I actually started to look into it but I am very busy with my day job at the moment so it will take a while because it's a bit complex. But it would definitely be awesome to have this feature. I'll update this when I have a chance to dedicate more time to it :)

**Comment by flobaader** [comment]
would it be possible to support you in this? The tool could be very interesting for us as a company (and certainly for many others).

**Comment by vitobotta** [comment]
At the moment I am very busy with a migration, so I can only work on this tool in my free time. I'll try to work on it next week if I manage.

**Comment by vitobotta** [comment]
Closing - I've added this feature request to the backlog https://github.com/vitobotta/hetzner-k3s/projects/1#card-77398959

**Comment by vitobotta** [comment]
Hi, dunno if you are still interested but today I released a new version with support for autoscaling :) I had this issue in the task notes so i thought I'd let you know.

**Comment by Xalaxis** [comment]
@vitobotta Thanks for the ping to the issue! Definitely a feature I'm interested in playing with in the future :)
