### ISSUE TITLE
Enable Backups for Kubernetes Master(s)

### ISSUE THREAD

**Issue by flobaader** [vitobotta/hetzner-k3s#52]
Do you think it would be a good idea to create backups of the k3s masters with hetzner in order to further improve reliability of the cluster?
Or maybe support an external datastore as mentioned here: https://rancher.com/docs/k3s/latest/en/installation/ha/

**Comment by vitobotta** [comment]
External datastore could be a possibility. I haven't looked into how to back up and restore the embedded etc.

**Comment by vitobotta** [comment]
Closing - Added https://github.com/vitobotta/hetzner-k3s/projects/1#card-77398937 and https://github.com/vitobotta/hetzner-k3s/projects/1#card-77399030 for the two suggested features.
