### ISSUE TITLE
Hetzner CSI and Cloud Controller Manager are not being installed on v0.5.0

### ISSUE THREAD

**Issue by melalj** [vitobotta/hetzner-k3s#54]
I get this error message at the end when I create a cluster:

```
Please ensure kubectl is installed and in your PATH.
```

(I have added `enable_ipsec_encryption: true` to the config file)

This started to happen on a v0.5.0, while it's working properly on v0.4.8

**Comment by vitobotta** [comment]
Uhm as the error suggests it seems that you don't have kubectl in your PATH. The change between 0.4.8 and 0.5.0 is that in 0.4.8 I was using a Ruby gem to apply the manifests for the cloud controller manager, the CSI driver and the system upgrade controller, but that gem doesn't seem to be actively maintained and caused problems with Ruby upgrades.

So I simplified things and am now just using kubectl to apply the relevant manifests. Ensure that kubectl is available in your PATH. Which OS are you on?

**Comment by melalj** [comment]
I'm on macOS 12.0.1 and I actually used the docker command to create the cluster. So the kubectl should be on the docker image not on my computer.

**Comment by vitobotta** [comment]
Good point, I forgot about that detail in the Docker image when building the last one. Can you use the Ruby gem for now? I will update the Docker image as soon as I have a little time.

**Comment by melalj** [comment]
I ended using the 0.4.8 version and it worked for my usage :)

**Comment by vitobotta** [comment]
Cool. I'll let you know when I have updated the Docker image.

**Comment by vitobotta** [comment]
Image 0.5.0 has been fixed.
