### ISSUE TITLE
need advice on node selection

### ISSUE THREAD

**Issue by quanhua92** [vitobotta/hetzner-k3s#55]
Hi,
I am on a budget ($50/month) so I wonder what the best choice of the nodes is:
1) 3 master CPX21 (7.83 * 3 = $23.49) + 3 worker CPX21 (7.83 * 3 = $23.49) => $46.98 / month = 9 vCPU 12GB RAM
2) 3 master CPX11 (4.53 * 3 = $13.59) + 3 worker CPX21 (7.83 * 3 = $23.49) => $37.08 / month = 9 vCPU 12GB RAM
3) 3 master CPX11 (4.53 * 3 = $13.59) + 3 worker CPX31 (14.08 * 3 = $42.24) => $55.83 / month = 12 vCPU 24GB RAM
4) 6 CPX21 with allow workload on masters => $46.98 / month = 18 vCPU 24GB RAM
5) 3 master CPX21 with allow workload on masters => $23.49 / month = 9 vCPU 12GB RAM
6) 3 master CPX31 with allow workload on masters => $42.24 / month = 12 vCPU 24GB RAM

My workload includes:
- MySQL Clusters + BlockStorage
- Next.js Server for eCommerce website with BunnyCDN for static assets
- MinIO S3 Object + BlockStorage
- Private Docker Registry + BlockStorage

Thank you very much.

**Comment by vitobotta** [comment]
Hi,

CPX11 should be enough for the masters if you don't schedule workloads on them. It's recommended to keep masters and workers separate if this is a production environment. As for the worker nodes it really depends on the resources required by those workloads. From looking at that list I would probably go with CPX31 for the worker nodes.

**Comment by quanhua92** [comment]
Thank you for your quick advice.
