### ISSUE TITLE
Instruction (Draft + Questions)

### ISSUE THREAD

**Issue by TitanFighter** [vitobotta/hetzner-k3s#58]
Hi.

I have been trying to run [raw] Kubernetes on Hetzner for the last ~7 days without luck and just your project and [this](https://github.com/vitobotta/hetzner-k3s/issues/13#issuecomment-901857297) answer helped me to succeed. As a result I want to prepare a full instruction for others (which you can add to the wiki or to the README).

Below is the draft and a couple of questions which I want to clarify. Would be sweet if you can check if everything is correct and provide answers.

### Installation of "hello-world" project.

For testing we are going to use this "hello-world" app - https://gist.githubusercontent.com/vitobotta/6e73f724c5b94355ec21b9eee6f626f1/raw/3036d4c4283a08ab82b99fffea8df3dded1d1f78/deployment.yaml

1. Install `kubectl` on your computer: https://kubernetes.io/docs/tasks/tools/#kubectl
2. Install `Helm` on your computer: https://helm.sh/docs/intro/install/
3. Install `hetzner-k3s` on your computer: https://github.com/vitobotta/hetzner-k3s#installation
4. Create file `hetzner-k3s_cluster_config.yaml` with the config below (this is a config for High Available (HA) cluster with 3 master nodes + 3 worker nodes. You can use 1+1 for testing):

```
hetzner_token: nRTJFfhIGNT..........
cluster_name: hello-world  # hetzner-k3s gives the next names to hosts: hellow-world-cpx21-master1 / hellow-world-cpx21-pool-cpx21-worker1
kubeconfig_path: "./kubeconfig"  # or /cluster/kubeconfig if you are going to use Docker
k3s_version: v1.23.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: ash
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
worker_node_pools:
- name: cpx41
  instance_type: cpx21
  instance_count: 3
enable_encryption: true
```

5. Create cluster: `hetzner-k3s create-cluster --config-file hetzner-k3s_cluster_config.yaml`
6. `hetzner-k3s` automatically creates `kubeconfig` for the cluster in the directory of your computer where you run the tool,
so you can either copy the `kubeconfig` file to `~/.kube/config` if it's the only cluster, or run `export KUBECONFIG=./kubeconfig`
in the same directory to access the cluster. Then you can interact with your cluster via `kubectl` installed in the 1st step.

TIP: If you don't want to run `kubectl apply ...` every time, you can store all configs in some folders and then run `kubectl apply -f /path/to/configs/ -R`.

7. Create file: `touch ingress-nginx-annotations.yaml`
8. Add annotations to the file: `nano ingress-nginx-annotations.yaml`
```
# INSTALLATION
# 1. Install Helm: https://helm.sh/docs/intro/install/
# 2. Add ingress-nginx help repo: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# 3. Update information of available charts locally from chart repositories: helm repo update
# 4. Install ingress-nginx:
# helm upgrade --install \
# ingress-nginx ingress-nginx/ingress-nginx \
# -f ./ingress-nginx-annotations.yaml \
# --namespace ingress-nginx \
# --create-namespace

# LIST of all ANNOTATIONS: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/internal/annotation/load_balancer.go

controller:
  kind: DaemonSet
  service:
    annotations:
      # Germany:
      # - nbg1 (Nuremberg)
      # - fsn1 (Falkensteing)
      # Finland:
      # - hel1 (Helsinki)
      # USA:
      # - ash (Ashburn, Virginia)
      # Without this the load balancer won't be provisioned and will stay in "pending" state.
      # The state you can check via "kubectl get svc -n ingress-nginx"
      load-balancer.hetzner.cloud/location: ash

      # Name of load balancer. This name you will see in your Hetzner's cloud console (site) at the "Your project -> Load Balancers" page
      load-balancer.hetzner.cloud/name: WORKERS_LOAD_BALANCER_NAME

      # Ensures that the communication between the load balancer and the cluster nodes happens through the private network
      load-balancer.hetzner.cloud/use-private-ip: "true"

      # [ START: If you care about seeing the actual IP of the client then use these two annotations ]
      # - "uses-proxyprotocol" enables the proxy protocol on the load balancers so that ingress controller and
      # applications can "see" the real IP address of the client.
      # - "hostname" is needed just if you use cert-manager (LetsEncrypt SSL certificates). You need to use it in order
      # to fix fails http01 challenges of "cert-manager" (https://cert-manager.io/docs/).
      # Here (https://github.com/compumike/hairpin-proxy) you can find a description of this problem.
      # To be short: the easiest fix provided by some providers (including Hetzner) is to configure the load balancer so
      # that it uses a hostname instead of an IP.
      load-balancer.hetzner.cloud/uses-proxyprotocol: 'true'

      # 1. "yourDomain.com" must be configured in the DNS correctly to point to the Nginx load balancer, 
      # otherwise the provision of certificates won't work;
      # 2. if you use a few domains, specify any one.
      load-balancer.hetzner.cloud/hostname: yourDomain.com
      # [ END: If you care about seeing the actual IP of the client then use these two annotations ]

      load-balancer.hetzner.cloud/http-redirect-https: 'false'
```

9. Add ingress-nginx Helm repo: `helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx`
10. Update information of available charts locally from chart repositories: `helm repo update`
11. Install ingress-nginx:
```
helm upgrade --install \
ingress-nginx ingress-nginx/ingress-nginx \
-f ~/.kube/ingress-nginx-annotations.yaml \
--namespace ingress-nginx \
--create-namespace
```

TIP: Just in case you need to delete it: `helm uninstall ingress-nginx -n ingress-nginx`.
Be careful, this will delete current Hetzner's load balancer as a result when you install a new ingress controller,
new Hetzner's load balancer possibly will be created with a new public IP address.

12. In a few minutes check that the "EXTERNAL-IP" column has IP instead of "pending": `kubectl get svc -n ingress-nginx`
13. Open your Hetzner's cloud console (site), "Your project -> Load Balancers" and find PUBLIC IP in front of the name you used with "load-balancer.hetzner.cloud/name: WORKERS_LOAD_BALANCER_NAME" annotation. Copy/Remember this IP.
14. Download hello-world app: `curl https://gist.githubusercontent.com/vitobotta/6e73f724c5b94355ec21b9eee6f626f1/raw/3036d4c4283a08ab82b99fffea8df3dded1d1f78/deployment.yaml --output hello-world.yaml`
15. Change the file (add annotation + add Hetzner's Load Balancer IP Address): `nano hello-world.yaml`
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:                             # <<<--- Add annotation
    kubernetes.io/ingress.class: nginx     # <<<--- Add annotation
spec:
  rules:
  - host: hello-world.IP_FROM_STEP_13.nip.io # <<<--- ADD IP FROM THE STEP 13.
  ....
```

16. Install hello-world app: `kubectl apply -f hello-world.yaml`
17. Check http://hello-world.IP_FROM_STEP_13.nip.io
You should see the RANCHER Hello world! page.
"host.IP_FROM_STEP_13.nip.io" (the key part is ".nip.io") is just a quick way to test things without configuring DNS (a query to a hostname ending in nip.io simply returns the IP address it finds in the hostname itself).
18. In order to connect yourDomain.com, you need to:
 - assign IP address from the step 13 to your domain in DNS panel of your domain registrar;
 - change "- host: hello-world.IP_FROM_STEP_13.nip.io" to "- host: yourDomain.com";
 - `kubectl apply -f hello-world.yaml`
 - wait 1-30 mins until DNS records are updated.

If you need LetsEncrypt
19. `load-balancer.hetzner.cloud/uses-proxyprotocol: "true"` annotation requires `use-proxy-protocol: "true"` for ingress-nginx, so let's create file: `touch ingress-nginx-configmap.yaml`
20. Add content to just created file: `nano ingress-nginx-configmap.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  # Do not change name - this is the name required by Nginx Ingress Controller
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-proxy-protocol: "true"
```

21. Apply config map: `kubectl apply -f ./ingress-nginx-configmap.yaml`
22. Add LetsEncrypt Helm repo: `helm repo add jetstack https://charts.jetstack.io`
23. Update information of available charts locally from chart repositories: `helm repo update`
24. Install LetsEncrypt certificates issuer:

```
helm upgrade --install \
--namespace cert-manager \
--create-namespace \
--set installCRDs=true \
cert-manager jetstack/cert-manager
```

25. Create file `lets-encrypt.yaml` with content:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: YOUR@EMAIL.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
```

26. Apply file: `kubectl apply -f ./lets-encrypt.yaml`

27. Change `nano hello-world.yaml`:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"    # <<<--- Add annotation
    kubernetes.io/tls-acme: "true"                        # <<<--- Add annotation
spec:
  rules:
  - host: yourDomain.com  # <<<---- Your real domain
  tls: # <<<---- Add this block
  - hosts:
    - yourDomain.com
  ....
```

28. Apply changes: `kubectl apply -f ./hello-world.yaml`

Instruction is based on the README + [this answer](https://github.com/vitobotta/hetzner-k3s/issues/13#issuecomment-901857297).

#### 1. What Load Balancers will be installed?
`hetzner-k3s` installs/configures load balancer(s) for you via [Hetzner's cloud controller manager](https://github.com/hetznercloud/hcloud-cloud-controller-manager).
They cost money. The cheapest right now is 5 EUR/month.

If you are going to have a High Available (HA) cluster, you need to have 3/5/7/... (odd number) master nodes.
In this case you will get 2 Hetzner's load balancers:
- one for Kubernetes API (this one will be installed automatically by hetzner-k3s);
- one for workers (for this one you need to add annotation "load-balancer.hetzner.cloud/location: XYZ" to ingress-nginx).

In case if you need to have just 1 master node, there will be just 1 Hetzner's load balancer - for workers (you need to add annotation "load-balancer.hetzner.cloud/location: XYZ" to ingress-nginx).

#### 2. Can we use "rules" block of ingress-nginx (the one which Kubernetes uses as a LoadBalancer) instead of creating our own "per-app" ingress as well as cert-manager like shown below
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-nginx
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   cert-manager.io/cluster-issuer: letsencrypt-prod
   kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - yourDomain.com
    secretName: letsencrypt-certs
  rules:
  - host: yourDomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myService
            port:
              number: 80
```
?

I usually prefer to separate the ingresses for each app but I guess that would work too. I also usually keep apps in separate namespaces, so in that case I need to have separate ingress resources.

#### 3. Is it possible to use for example MetalLB instead of Hetzner's LB?
There is a way to use MetalLB with floating IPs in Hetzner Cloud but I don't recommend it. The setup with standard load balancers is much simpler and load balancers are not that much more expensive than floating IPs so IMO there's no point using MetalLB.

#### 4. How to create and push docker images to a repository and how to allow kubernetes to work with this image (gitlab example)?
On a computer which creates an image:
- `docker login registry.gitlab.com`
- `docker build -t registry.gitlab.com/COMPANY_NAME/REPO_NAME:IMAGE_NAME -f /some/path/to/Dockerfile .`
- `docker push registry.gitlab.com/COMPANY_NAME/REPO_NAME:IMAGE_NAME`

On a computer which runs kubernetes:
- generate secret to access images: `kubectl create secret docker-registry gitlabcreds --docker-server=https://registry.gitlab.com --docker-username=MYUSER --docker-password=MYPWD --docker-email=MYEMAIL -n NAMESPACE_OF_YOUR_APP -o yaml > docker-secret.yaml`
- apply secret: `kubectl apply -f docker-secret.yaml -n NAMESPACE_OF_YOUR_APP`

#### 5. How to check how much resources nodes/pods use?
- Install metrics-server https://github.com/kubernetes-sigs/metrics-server
- Then use either `kubectl top nodes` or `kubectl top pods -A`

#### 6. What is Ingress?
There are 2 types of "ingress" -> `Ingress Controller` and `Ingress Resources`.
To simplify everything, in the case of Nginx...
- Ingress Controller is Nginx itself (this is `kind: Ingress`), Ingress Resources are services (ie. `kind: Service`).
- Ingress Controller has different annotations (rules). You can use them inside `kind: Ingress` as a result such rules become "global" and inside `kind: Service` as a result such rules become "local" (service-specific).
- Ingress Controller consists of a Pod and a Service. The Pod runs the Controller, which constantly polls the /ingresses endpoint on the API server of your cluster for updates to available Ingress Resources.

## Useful commands
kubectl get service [serviceName] -A or -n [nameSpace]  
kubectl get ingress [ingressName] -A or -n [nameSpace]  
kubectl get ingress [podName] -A or -n [nameSpace]  
kubectl get all -A  
kubectl get events -A  
helm ls -A  
helm uninstall [name] -n [nameSpace]  
kubectl -n ingress-nginx get svc  
kubectl describe ingress -A  
kubectl describe svc -n ingress-nginx  
kubectl delete configmap nginx-config -n ingress-nginx  
kubectl rollout restart deployment -n NAMESPACE_OF_YOUR_APP
kubectl logs my-pod -n NAMESPACE_OF_YOUR_APP

`kubectl get all -A` does not include "ingress", as a result you need to use `kubectl get ing -A`

##  Useful links
Cheat Sheet - https://kubernetes.io/docs/reference/kubectl/cheatsheet/  
A visual guide on troubleshooting Kubernetes deployments - https://learnk8s.io/troubleshooting-deployments

----

## Questions
1. `load-balancer.hetzner.cloud/name: ANY_NAME` Is it correct that here can be any_name?

2. I have config with 3 master nodes + 3 worker nodes.
In Hetzner's cloud console I see 2 Load Balancers: one is "CLUSTER_NAME-api" and another one "ANY_NAME". Is it correct or there should be just one Load Balancer as a result something configured incorrectly?
Asking because here in the images there is just one load balancer - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/ha-topology/

3. Regarding `load-balancer.hetzner.cloud/location: ash`.
Once this annotation added to the ingress-nginx, I see that `kubectl get srv -n ingress-nginx` starts to show `EXTERNAL-IP` 10.0.0.8 instead of "pending". Is this IP correct? I thought it should be public IP.

4. `load-balancer.hetzner.cloud/hostname: <a valid fqdn>`
As far as I understand, this annotation must be added to the ingress-nginx, right? If so, as I know fqdn could be just hostname (server name) and could be HOSTNAME.yourDomain.com
If I have 3 master nodes and 3 worker nodes and cluster services few domains, what value should be provided as `<a valid fqdn>`?

5. Can we use "rules" block of `ingress-nginx` (the one which Kubernetes uses as a LoadBalancer) instead of creating our own "per-app" ingress as well as cert-manager like
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-nginx
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
   cert-manager.io/cluster-issuer: letsencrypt-prod
   kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - yourDomain.com
    secretName: letsencrypt-certs
  rules:
  - host: yourDomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myService
            port:
              number: 80
```
?
If yes, is there any reason to use per-app ingress rather than to have everything in one ingress?

6.1 Is it possible to use for example MetalLB instead of Hetzner's LB?
6.2 Why do we need Hetzner's LB at all? As I understand (taking into account this answer https://stackoverflow.com/a/56323161/4992248) it is possible to connect public virtual server's IP to ingress-nginx somehow and this should be enough. Ive tried it without luck. Am I wrong or it is possible? If possible, how? If not possible, why? With docker everything is simple and works without Hetzner's Load Balancer.

**Comment by vitobotta** [comment]
Hi and awesome job! I will gladly add this to a page in the Wiki. Thanks for taking the time to write this.

As for your questions: 

1. I am not aware of many restrictions but it's probably better to avoid special characters etc in the name.
2. The "<cluster-name>-api" load balancer is the one created automatically for the Kubernetes API by my tool, while any other load balancers in the project are created for your workloads like Nginx etc.
3. Uhm yes you should see a public IP, not a private one. Can you share the full config that caused this?
4. The value can be any valid domain name that is reachable from the Internet, so you will need to configure DNS so that domain/hostname points to the IP of the load balancer that is created. Of course you need to configure the DNS after the load balancer is created because you wouldn't have the IP address yet otherwise. Note that this configuration is only necessary if you want to enable "proxy protocol". The proxy protocol is required when using a load balancer so that your apps can see the real IP of the client, and not the IP of the load balancer itself. For this to work, the proxy protocol must be enabled on both the load balancer (there is a special annotation for that) and Nginx config or other workload config. The annotation you mentioned about the fqdn is required so that things like cert-manager can issue certificates using the HTTP01 challenge method. It's a long story, but in short if you use cert-manager for certificates and at the same time you need the proxy protocol to see the correct IPs of your users, then you need to add the annotation with the fqdn. Otherwise it won't work.
5. I usually prefer to separate the ingresses for each app but I guess that would work too. I also usually keep apps in separate namespaces, so in that case I need to have separate ingress resources.
6. 1. There is a way to use MetalLB with floating IPs in Hetzner Cloud but I don't recommend it. The setup with standard load balancers is much simpler and load balancers are not that much more expensive than floating IPs so IMO there's no point using MetalLB. 
6. 2. You can also install Nginx ingress configured to use host ports instead of using a load balancer. That way you can then configure your DNS to point to the IPs of the nodes directly. The problem with that is that if you replace the nodes or something you need to remember to update the DNS configuration right away with the new IPs. When using a normal load balancer instead, the IP is stable regardless of what happens to the nodes.

**Comment by TitanFighter** [comment]
> 2. The "-api" load balancer is the one created automatically for the Kubernetes API by my tool, while any other load balancers in the project are created for your workloads like Nginx etc.

As I said in Hetzner's cloud console I have 2 load balancers + my External IP looks like 10.0.0.8 instead of public IP 5.161.33.14. By assigning 5.161.33.14 to myDomain.com in DNS settings of domain registrar I can connect to my app via mydomain.com. Your answer looks like in case of 3+3 config I should have 2 load balancers, BUT:
- in Hetzner's Cloud Console at "My project -> Load Balancers" page I should see JUST ONE Load Balancer;
- the 2nd load balancer is internal Kubernetes' load balancer for workloads, as a result this load balancer should not be created/listed in Hetzner's Cloud Console at "My project -> Load Balancers".

Am I right?

![image](https://user-images.githubusercontent.com/12687911/151665564-56c0f258-a3a4-41a4-b5d7-e436bdc402ea.png)

> 3. Uhm yes you should see a public IP, not a private one. Can you share the full config that caused this?

```
hetzner_token: nRTJFfhIGNTqomu......
cluster_name: us-east
kubeconfig_path: "/cluster/kubeconfig"
k3s_version: v1.23.3+k3s1
public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: ash
schedule_workloads_on_masters: false
masters:
  instance_type: cpx21
  instance_count: 3
worker_node_pools:
- name: cpx41
  instance_type: cpx41
  instance_count: 2
enable_ipsec_encryption: true
```

```
# ingress-nginx-annotations.yaml

controller:
  kind: DaemonSet
  service:
    annotations:
      load-balancer.hetzner.cloud/location: ash
      load-balancer.hetzner.cloud/name: us-east
      load-balancer.hetzner.cloud/use-private-ip: "true"
```
`helm upgrade --install \
ingress-nginx ingress-nginx/ingress-nginx \
-f ./ingress-nginx-annotations.yaml \
--namespace ingress-nginx \
--create-namespace`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: frontend-prod
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: rancher/hello-world
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: frontend-prod
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  namespace: frontend-prod
spec:
  rules:
  - host: hello-world.5.161.33.14.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
```

```
root@us-east-cpx21-master1:~# kubectl describe ingress -A
Name:             hello-world
Labels:           <none>
Namespace:        frontend-prod
Address:          10.0.0.8,2a01:4ff:f1:6bd::1,5.161.33.14
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                            Path  Backends
  ----                            ----  --------
  hello-world.5.161.33.14.nip.io  
                                  /   hello-world:80 (10.244.3.16:80)
Annotations:                      kubernetes.io/ingress.class: nginx
                                  nginx.ingress.kubernetes.io/rewrite-target: /
Events:                           <none>
```
```
root@us-east-cpx21-master1:~# kubectl get svc -A
NAMESPACE                NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP                               PORT(S)                      AGE
default                  kubernetes                           ClusterIP      10.43.0.1       <none>                                    443/TCP                      22h
ingress-nginx            ingress-nginx-controller             LoadBalancer   10.43.22.85     10.0.0.8,2a01:4ff:f1:6bd::1,5.161.33.14   80:32731/TCP,443:32653/TCP   15h
ingress-nginx            ingress-nginx-controller-admission   ClusterIP      10.43.35.59     <none>                                    443/TCP                      15h
kube-system              hcloud-csi-controller-metrics        ClusterIP      10.43.207.86    <none>                                    9189/TCP                     21h
kube-system              hcloud-csi-node-metrics              ClusterIP      10.43.143.249   <none>                                    9189/TCP                     21h
kube-system              kube-dns                             ClusterIP      10.43.0.10      <none>                                    53/UDP,53/TCP,9153/TCP       22h
frontend-prod   hello-world                          ClusterIP      10.43.239.189   <none>                                    80/TCP                       15h
root@us-east-cpx21-master1:~# 
root@us-east-cpx21-master1:~# 
root@us-east-cpx21-master1:~# kubectl get svc -n ingress-nginx
NAME                                 TYPE           CLUSTER-IP    EXTERNAL-IP                               PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.43.22.85   10.0.0.8,2a01:4ff:f1:6bd::1,5.161.33.14   80:32731/TCP,443:32653/TCP   15h
ingress-nginx-controller-admission   ClusterIP      10.43.35.59   <none>                                    443/TCP                      15h
root@us-east-cpx21-master1:~# 
root@us-east-cpx21-master1:~# 
root@us-east-cpx21-master1:~# 
root@us-east-cpx21-master1:~# kubectl get all -A
NAMESPACE                NAME                                                   READY   STATUS    RESTARTS      AGE
ingress-nginx            pod/ingress-nginx-controller-5ckgk                     1/1     Running   0             15h
ingress-nginx            pod/ingress-nginx-controller-qrrn9                     1/1     Running   0             15h
kube-system              pod/coredns-5789895cd-r6cb2                            1/1     Running   0             22h
kube-system              pod/hcloud-cloud-controller-manager-6d954d5747-62sct   1/1     Running   0             21h
kube-system              pod/hcloud-csi-controller-0                            5/5     Running   0             21h
kube-system              pod/hcloud-csi-node-ct5qq                              3/3     Running   2 (21h ago)   21h
kube-system              pod/hcloud-csi-node-gkpc6                              3/3     Running   2 (21h ago)   21h
kube-system              pod/hcloud-csi-node-gn89k                              3/3     Running   2 (21h ago)   21h
kube-system              pod/hcloud-csi-node-lxklp                              3/3     Running   2 (21h ago)   21h
kube-system              pod/hcloud-csi-node-wnhfl                              3/3     Running   2 (21h ago)   21h
system-upgrade           pod/system-upgrade-controller-6ddbc4c6cd-24zl5         1/1     Running   0             21h
frontend-prod   pod/hello-world-55d7fbc94b-578dt                       1/1     Running   0             15h

NAMESPACE                NAME                                         TYPE           CLUSTER-IP      EXTERNAL-IP                               PORT(S)                      AGE
default                  service/kubernetes                           ClusterIP      10.43.0.1       <none>                                    443/TCP                      22h
ingress-nginx            service/ingress-nginx-controller             LoadBalancer   10.43.22.85     10.0.0.8,2a01:4ff:f1:6bd::1,5.161.33.14   80:32731/TCP,443:32653/TCP   15h
ingress-nginx            service/ingress-nginx-controller-admission   ClusterIP      10.43.35.59     <none>                                    443/TCP                      15h
kube-system              service/hcloud-csi-controller-metrics        ClusterIP      10.43.207.86    <none>                                    9189/TCP                     21h
kube-system              service/hcloud-csi-node-metrics              ClusterIP      10.43.143.249   <none>                                    9189/TCP                     21h
kube-system              service/kube-dns                             ClusterIP      10.43.0.10      <none>                                    53/UDP,53/TCP,9153/TCP       22h
frontend-prod   service/hello-world                          ClusterIP      10.43.239.189   <none>                                    80/TCP                       15h

NAMESPACE       NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
ingress-nginx   daemonset.apps/ingress-nginx-controller   2         2         2       2            2           kubernetes.io/os=linux   15h
kube-system     daemonset.apps/hcloud-csi-node            5         5         5       5            5           <none>                   21h

NAMESPACE                NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
kube-system              deployment.apps/coredns                           1/1     1            1           22h
kube-system              deployment.apps/hcloud-cloud-controller-manager   1/1     1            1           21h
system-upgrade           deployment.apps/system-upgrade-controller         1/1     1            1           21h
frontend-prod   deployment.apps/hello-world                       1/1     1            1           15h

NAMESPACE                NAME                                                         DESIRED   CURRENT   READY   AGE
kube-system              replicaset.apps/coredns-5789895cd                            1         1         1       22h
kube-system              replicaset.apps/hcloud-cloud-controller-manager-6d954d5747   1         1         1       21h
system-upgrade           replicaset.apps/system-upgrade-controller-6ddbc4c6cd         1         1         1       21h
frontend-prod   replicaset.apps/hello-world-55d7fbc94b                       1         1         1       15h

NAMESPACE     NAME                                     READY   AGE
kube-system   statefulset.apps/hcloud-csi-controller   1/1     21h
```

Is there anything else I can provide?

> 4. ...

In the 4th point, saying "load balancer" are you talking about `load balancers in the project are created for your workloads like Nginx`, right? or about "-api" load balancer? This is one thing that confuses me (ie there are few load balancers and from the context I don't understand about which one it's talking about). I assume that you are talking about Nginx.

> The value can be any valid domain name that is reachable from the Internet, so you will need to configure DNS so that domain/hostname points to the IP of the load balancer that is created.

`configure DNS so that domain/hostname points to the IP of the load balancer that is created` part I understand and it has been done. I do not understand another thing. If you are talking about Nginx... we have one load balancer (Nginx) with one IP for all workloads. These workloads can provide service for 10 domains, but we have just one Nginx... with one `load-balancer.hetzner.cloud/hostname: <a valid fqdn>`, is it correct? Or `load-balancer.hetzner.cloud/hostname: <a valid fqdn>` must be used for each app, so one app/domain = one annotation?

> domain/hostname points to the IP of the load balancer that is created

The IP you are talking here, is it IP shown under External IP at `kubectl get srv -n ingress-nginx`? And in my case must be public ip rather than local?

I suppose you have a HA cluster which serves few domains. Can you simply show an example of `<a valid fqdn>`?

> 7. ii. You can also install Nginx ingress configured to use host ports instead of using a load balancer. That way you can then configure your DNS to point to the IPs of the nodes directly. The problem with that is that if you replace the nodes or something you need to remember to update the DNS configuration right away with the new IPs. When using a normal load balancer instead, the IP is stable regardless of what happens to the nodes.

Yeah, host port way I have tested, but probably my problem is that Im thinking in a Docker-style logic, where I can prepare nginx container as a reverse proxy server with a list of domains and behind this reverse proxy I can up as many apps as I need.

Do I understand correctly, that with Kubernetes the next scheme does not work:
[client/internet] -> [server with public ip -> ingress-nginx -> app1 / app2 / appX ]

and instead we need something like this:
[client/internet] -> [Cloud's load balancer] -> [ingress-nginx -> app1 / app2 / appX ]
?

----

I updated a bit Instruction, added FAQs section. I want to add `cert-manager` and `rancher` from your answer, but I want to test it myself first (do not want to add to the instruction something I do not understand / did not check). I want to do this after fixing of EXTERNAL-IP issue and after clear understanding how many Load Balancers Hetzner should have (1 or 2).

**Comment by vitobotta** [comment]
Yes that config with 2 load balancers is correct in a HA setup. In the describe for the nginx load balancer I see the public IP `LoadBalancer Ingress:     5.161.33.14` - this seems correct. I am not sure why it shows the private IP when you do a `get` command, maybe it's because you've used the private ip annotation, not sure / can't remember.

Yes, by `load balancers in the project are created for your workloads` I was referring to load balancers for workloads, not the API load balancer.

Next point: you have one ingressl _controller_, but you can create any number of ingress _resources_ for your workloads. The annotation `load-balancer.hetzner.cloud/hostname` is only for the ingress controller so that it's applied to the load balancer. You don't need that in ingress resources.

> The IP you are talking here, is it IP shown under External IP at kubectl get srv -n ingress-nginx? And in my case must be public ip rather than local?

In the DNS you should use the public IP as shown in the describe command for the nginx svc. Like I said I am not sure why it's showing the private IP for you as external ip when you do a `get` command. 

> Do I understand correctly, that with Kubernetes the next scheme does not work:
[client/internet] -> [server with public ip -> ingress-nginx -> app1 / app2 / appX ]

This works only if you set up nginx without load balancer. So DNS points directly to the nodes, and nginx proxies requests to the apps.

> and instead we need something like this:
[client/internet] -> [Cloud's load balancer] -> [ingress-nginx -> app1 / app2 / appX ]

This is the typical/recommended setup, yes.

**Comment by TitanFighter** [comment]
Little update. Do not close this issue, I remember about it and already have some updates - just busy with migration of projects from docker to kubernates and after that I will be able to finish this instruction.

**Comment by vitobotta** [comment]
Ok, I'll leave it open for now.

**Comment by TitanFighter** [comment]
@vitobotta [Instruction + FAQs + Useful commands + Useful links] block have been updated. Please check it when you have time and if everything is correct, you can add it to Wiki page and close this issue.

Thank you for your work and help!

**Comment by yoplait** [comment]
Great post! ... Thanks for such informational wiki @vitobotta @TitanFighter

**Comment by vitobotta** [comment]
> @vitobotta [Instruction + FAQs + Useful commands + Useful links] block has been updated. I did not install Rancher, because I do not need it, as a result I did not add steps of installation of Rancher to the instruction. Please check it when you have time and if everything is correct you can add it to Wiki page and close this issue. Also I think would be good to add a link to README, because a lot of people simply forget that github has Wiki page.
> 
> Thank you for your work and help!

Awesome stuff! 👍 

A few comments:
- you don't need to SSH into a master to install in order to install Helm charts for Nginx and other stuff. The kubeconfig for the cluster is automatically created in the directory of your computer where you run the tool. So you can either copy the kubeconfig file to ~/.kube/config if it's the only cluster, or run `export KUBECONFIG=./kubeconfig` in the same directory to access the cluster. Then you can interact with it as usual.
- about `load-balancer.hetzner.cloud/hostname` you could add that this hostname must be configured in the DNS correctly to point to the Nginx load balancer, otherwise the provision of certificates won't work.


Can you please send me the markdown for the wiki? I can't just copy and paste because the formatting gets lost. Thanks!

**Comment by TitanFighter** [comment]
> you don't need to SSH into a master 
As i understand, in this case it is necessary to install `kubectl` and `Helm` on my own computer, right? I've been thinking about this way but I like ssh way (just personal preference / habit). I added your info as an alternative approach as a TIP under step 4. If something is incorrect - fix it in the version I sent to your email.

> about load-balancer.hetzner.cloud/hostname you could add that this hostname must be configured
Added

> Can you please send me the markdown for the wiki? I can't just copy and paste because the formatting gets lost. Thanks!
Just sent, please check.

**Comment by vitobotta** [comment]
> > you don't need to SSH into a master
> 
> As i understand, in this case it is necessary to install `kubectl` and `Helm` on my own computer, right? I've been thinking about this way but I like ssh way (just personal preference / habit). I added your info as an alternative approach as a TIP under step 4. If something is incorrect - fix it in the version I sent to your email.
> 

Normally with Kubernetes you really don't touch any nodes directly. Most people connect to the cluster from the outside. I find it cumbersome to ssh into a master each time.

> > about load-balancer.hetzner.cloud/hostname you could add that this hostname must be configured
> 
> Added
> 
> > Can you please send me the markdown for the wiki? I can't just copy and paste because the formatting gets lost. Thanks!
> 
> Just sent, please check.

Do you mind using pastebin or similar? My email clients (Spark and Zoho) don't leave the markdown exactly as it is.

**Comment by TitanFighter** [comment]
1. I fully removed info about SSH. Thanks for pointing out the right direction;
2. Just sent a mail with a simple txt file with markdown syntax. This should work.

**Comment by vitobotta** [comment]
I'm sorry for the delay, but I finally got a chance to check the tutorial and add a page at https://github.com/vitobotta/hetzner-k3s/wiki/Tutorial:---Setting-up-a-cluster

A huge thanks for your contribution! Closing this for now but feel free to reopen if you have more comments etc :)
