### ISSUE TITLE
Pods can't reach pods on other nodes

### ISSUE THREAD

**Issue by arusa** [vitobotta/hetzner-k3s#59]
I'm quite new to Kubernetes. I installed one master and two workers using this tool and it worked quite well.
Then I tried to install cert-manager, but had problems and found out that resolving dns does not work because containers on one node can't reach containers on other nodes.
My research pointed me to problems with the CNI but I can't even see any configured CNI.
How is this supposed to work?
The virtual hetzner network has 10.0.0.0/16 configured and the pods are using 10.244.0.x, 10.244.1.x, 10.244.2.x
I think this needs a CNI to work? Should this work out of the box or do I need to configure a CNI?

**Comment by vitobotta** [comment]
The hetzner actual network range is unrelated to the pod/service ranges.

I assume you are using cert-manager with an ingress controller, right? In that case, did you by chance enable the proxy protocol for the load balancer? If yes you need an annotation to ensure that the load balancer is addressed by a DNS hostname pointing to its IP. You also need to configure proxy protocol in the ingress' configuration.

With these settings, when cert-manager attempts to make an HTTP01 challenge to issue a certificate, requests will go through the load balancer thanks to the hostname annotation. Without that annotation challenges will fail.

See https://github.com/vitobotta/hetzner-k3s#load-balancers for additional information.

**Comment by arusa** [comment]
Thanks for the detailed explanation!
Actually I am trying to install cert-manager with the DNS issuer. But my problem is that no pods are able to resolve anything because they can’t reach (and ping) the coredns service if they aren’t running on the same node as coredns.
I am wondering how it could even be possible for a container on one node to reach a container on another node.

**Comment by vitobotta** [comment]
If you try to query CoreDNS to resolve a hostname from a pod what do you get?

**Comment by vitobotta** [comment]
Closing due to the lack of updates. Feel free to reopen if you still have issues.
