### ISSUE TITLE
delete-cluster is not removing $cluster-api Loadbalancer

### ISSUE THREAD

**Issue by NicoWde** [vitobotta/hetzner-k3s#6]
Hello @vitobotta,

I played around with this fantastic tool now. I experienced that the API Loadbalancer is not going to be removed if a regular delete-cluster command is run.

Is this intentional to keep the IP or is this a bug? :)

Kind Regards
Nico

**Comment by vitobotta** [comment]
Hi @NicoWde ! glad that you like it:)

The firewall cannot be deleted until all the resources connected to it are removed. I did add some delay between the servers and deleting the firewall, but I've also noticed that sometimes it's not enough so the firewall doesn't actually get deleted yet if some servers are still attached.

I think one improvement I could make is to detach all the servers from the firewall explicitly first, and then delete both the servers and the firewall so this issue should no longer happen even if the deletion of the firewall is attempted before the deletion of a server attached to it. I believe that creations and deletions of resources are done asynchronously by Hetzner, so perhaps yeah sometimes a firewall is being deleted before one or more servers.

I'll make this change and push an update. Thanks for reporting. :)

**Comment by NicoWde** [comment]
hey! thanks for your response :) I think I ran into this exact problem. Also thanks for taking a look! :)

Is there some way to send you some wine from Germany? :)

**Comment by vitobotta** [comment]
LOL I am afraid I can't drink wine but thanks a lot for the thought, I appreciate :D

**Comment by vitobotta** [comment]
Hi @NicoWde - this has been fixed in 0.4.0. Now the targets (servers) are removed from the load balancer before deleting it so it should no longer happen. I'm closing this but feel free to reopen if you still have problems.
