### ISSUE TITLE
Unable to use existing Network

### ISSUE THREAD

**Issue by ramzcode** [vitobotta/hetzner-k3s#62]
Is there a way to reuse an existing hcloud network while creating with the cluster from the scratch. 
Unable to find options or KB that explains modifying the network properties

what i am trying to do:
Create a cluster with a network that was created manually created without using the default 10.0.0.0/16 CIDR

**Comment by vitobotta** [comment]
Hi, you should be able to use an existing network if you name it with the same name as the cluster. If a network with the name of the cluster already exists, the tool skips creating one.

**Comment by ramzcode** [comment]
Yes went through your code and found it. But have a query WRT flannel CIDR cause it is same and also cluster pods and service use unique IP addressing.

Please advice how can this be handled

**Comment by vitobotta** [comment]
What are you trying to do? Can you clarify?

**Comment by ramzcode** [comment]
Thanks for your hardwork and support. 

We are looking to spin multiple clusters and connect then using tools like kilo https://kilo.squat.ai/ 
Right now, we can use different private IP CIDR but the cluster flannel CIDR is same and this cause IP conflict and also confusions since SVC and PODs has the same IP like other clusters.

I could not see k3s level tweaking on this wonderful code, need your advice how can i do that. 

Requirement in one line is, need to create different K3s flannel CIDR's for different clusters

**Comment by vitobotta** [comment]
It seems that it is possible to specify pod/service cidr with k3s so I can add an option for that. I added this to the project board https://github.com/vitobotta/hetzner-k3s/projects/1#card-78048470

**Comment by ramzcode** [comment]
That sounds great. Thanks a lot

**Comment by ramzcode** [comment]
@vitobotta I can see, a new release with new features, hope this is not added yet.

**Comment by vitobotta** [comment]
Hi, what do you mean? I haven't added this yet but I will do it in the next few days.

**Comment by ramzcode** [comment]
Great thank you. I was in a doubt you already added it or yet to add.

**Comment by vitobotta** [comment]
Nope, not yet but pretty soon. It shouldn't be a big task.

**Comment by ramzcode** [comment]
once again thank you.

**Comment by ramzcode** [comment]
@vitobotta  Any update, kindly let me know

**Comment by vitobotta** [comment]
Not yet. I will try to do it in the weekend or one of these evening if I have time.

**Comment by ramzcode** [comment]
@vitobotta  Do we have any luck for this week ?

**Comment by vitobotta** [comment]
I have been super busy with my day job. I will try this week.

**Comment by ramzcode** [comment]
Thank you @vitobotta

**Comment by ramzcode** [comment]
@vitobotta Please advice if it is possible this week? Once again thank you for your wonderful support

**Comment by ramzcode** [comment]
@vitobotta Any Luck?

**Comment by vitobotta** [comment]
Hi, sorry for the delay but I only now have had time to work a bit on the project. Done in 0.5.9. Let me know if you run into issues. Closing for now since it's implemented.
