### ISSUE TITLE
403 Rate Limiting while creating a cluster

### ISSUE THREAD

**Issue by matthiasbruns** [vitobotta/hetzner-k3s#64]
Hello - I am being rate limited by Hetzner when trying to create a cluster.

This is the command I use

`docker run --rm -it -v ${PWD}:/cluster -v ${HOME}/.ssh:/tmp/.ssh vitobotta/hetzner-k3s:v0.5.2 create-cluster --config-file /cluster/config.yaml`

`---
hetzner_token: NOPE
cluster_name: k3s
kubeconfig_path: "./kubeconfig"
k3s_version: v1.21.3+k3s1
public_ssh_key_path: "~/.ssh/id_ed25519.pub"
private_ssh_key_path: "~/.ssh/id_ed25519"
ssh_allowed_networks:
  - 0.0.0.0/0
verify_host_key: false
location: nbg1
schedule_workloads_on_masters: false
masters:
  instance_type: cpx11
  instance_count: 3
worker_node_pools:
- name: tiny
  instance_type: cpx11
  instance_count: 2
- name: small
  instance_type: cpx21
  instance_count: 2
- name: big
  instance_type: cpx31
  instance_count: 2
enable_ipsec_encryption: true`

How can I solve this? It fails to create all master nodes

`
#<HTTP::Response/1.1 403 Forbidden {"Date"=>"Thu, 17 Feb 2022 15:17:56 GMT", "Content-Type"=>"application/json", "Content-Length"=>"202", "Connection"=>"close", "ratelimit-limit"=>"3600", "ratelimit-remaining"=>"3576", "ratelimit-reset"=>"1645111095", "x-correlation-id"=>"xxxx", "Strict-Transport-Security"=>"max-age=15724800; includeSubDomains", "Access-Control-Allow-Origin"=>"*", "Access-Control-Allow-Credentials"=>"true"}>
Error creating server k3s-cpx11-master1. Response details below:
`

Any change to implement a recovery mechanism or a pause?

**Comment by vitobotta** [comment]
Hi, it doesn't look like you hit a rate limit because the requests remaining were almost the hourly allotted number and the ratelimit-reset field says that the limit would be reset in a few seconds from that request. 403 means that something went wrong while authorizing the request, so I would check that the token is correct and has read and write permissions. Did any resources get created?

**Comment by vitobotta** [comment]
Good point, I had forgotten about that. Although if that's the case 403-unauthorized is a poor choice for the status code for those requests. They should return some more helpful error message explaining the limit.
