### ISSUE TITLE
volume is stuck on worker after shutdown

### ISSUE THREAD

**Issue by marc0olo** [vitobotta/hetzner-k3s#68]
I just tested what happens if I shutdown the worker where a volume is attached to.

the volume was created with the bitnami postgresql chart and my assumption was that the cluster detects this correctly and automatically attaches the volume to another worker.

is there any way to achieve this? did I miss some configuration? currently it doesn't work (at least in my setup)

**Comment by vitobotta** [comment]
That's a Kubernetes thing. It takes several minutes before it realizes that the node is down etc and that it has to move the pod, and therefore the volume to another node. You can try killing the pod forcefully. Depending on how the block storage is designed, sometimes the move is instant but in some cases it takes a while. Anyway it's not an issue with the tool so I'm closing as I am trying to keep these issues for problems and feature requests etc :)
