### ISSUE TITLE
Gitops question

### ISSUE THREAD

**Issue by jboesh** [vitobotta/hetzner-k3s#71]
Hi Vito!

At the moment I am creating the cluster with Docker locally on my laptop.
Would it also be possible to create AND manage the cluster via the Gitops principle?

So that I save the cluster configuration in Github and if I make a change there, it gets executed (automatically)?
This is useful so that you have version control and thus better control over new versions of, for example, k3s.

Tools like ArgoCD and Flux also use Gitops, but only for the workload. I'm looking for a way to control the infra as well.

Thanks!

**Comment by vitobotta** [comment]
Hi, I guess you can call the tool from CI too. Why not? :)

**Comment by jboesh** [comment]
Oh I was hoping you already had something like this working :-)

**Comment by vitobotta** [comment]
What do you mean? You can have a pipeline that on push, when updating the config file, just executes my tool with the new config file.

**Comment by jboesh** [comment]
haha it's not as simple as you describe.  I tried something in DroneCI but it keeps saying it can't find the config.yaml.  which needs your Docker run command to create the cluster.
do you have experience with a CI server where I can run the docker run command when changes are made to the config?

**Comment by vitobotta** [comment]
I haven't tried this in CI because I rarely need to change the formation of the cluster.

**Comment by jboesh** [comment]
I don't often either, but it's nice that you can manage everything via Gitops, so not only your workload, but also the infra everything in one place with version management and automated

**Comment by vitobotta** [comment]
Unfortunately I have only used Drone for a very short time and a long time ago so I am not sure of how you would solve this.
