### ISSUE TITLE
add external nodes to cluster

### ISSUE THREAD

**Issue by Privatecoder** [vitobotta/hetzner-k3s#72]
Hi @vitobotta

I'm having issues adding some external nodes to my K3s Cluster deployed using your tool and was wondering if you had an idea.

I added a single CPX11 machine as a cloud-interconnect _router_ which runs Wireguard:

- This _wg-cloud-interconnect_ has internal IP `10.0.0.11` and has been added to the existing firewall-group
- It has also been added to a new firewall-group which soley opens the machines Wireguard port (`51821`) for the connecting agents public IP
- The `wg0` interface IP of this machine is `10.1.0.1`
- In Hetzners networks config I added `10.1.0.0/24` destination to route through this machine (`10.0.0.11`)
- I added this route-config to all masters (1+2+3) with `ip route add 10.1.0.0/24 via 10.0.0.1 dev enp7s0`

On a vultr machine I set-up Wireguard as well with

- IP for `wg0` set to `10.1.0.2`
- AllowedIPs to `10.0.0.0/16`

also I set K3s's config (`/etc/systemd/system/k3s-agent.service`) to

```
 agent \
        '--node-name=vu-pool-test-worker1' \
        '--node-ip=10.1.0.2' \
        '--node-external-ip=xxx.xxx.xxx.xxx' \
        '--flannel-iface=wg0' \
```

What works:

- Ping all masters from the vultr machine (i.e. `10.1.0.2` to `10.0.0.x`)
- Ping the vultr machine from all masters (i.e. `10.0.0.x` to `10.1.0.2`)
- Add the node to K3s where it registers just fine **BUT** then immediately receives a `node.kubernetes.io/network-unavailable`
 taint with `NetworkUnavailable | True | XX xxx ago | [NoRouteCreated] RouteController failed to create a route`

Any thoughts?

**Comment by vitobotta** [comment]
This goes a bit beyond the scope of the tool but, anyway, did you also enable wireguard encryption with the config file for my tool?

**Comment by Privatecoder** [comment]
yes I did

**Comment by Privatecoder** [comment]
> This goes a bit beyond the scope of the tool but, anyway, did you also enable wireguard encryption with the config file for my tool?

This I know but then again it's such a wonderful tool which takes away so much manual work that I simply wasn't _ready_ to go down the _do-it-all-manually-path_ without asking you first ;)

**Comment by vitobotta** [comment]
I am not familiar with the details of how wireguard works, I am just wondering if the fact that wireguard is enabled in the cluster might interfere with what you are trying to do. I haven't tested adding external nodes. Maybe this could be a feature I could add. Why are you trying to add nodes from other providers?

**Comment by Privatecoder** [comment]
I will re-create the cluster with encryption disabled and report back.

To answer your question:

Because right now I am operation three clusters, one of them a K3s cluster using your tool @Hetzner with Rancher and the other two on vultr and DigitalOcean (as they have many more availability-regions than Hetzner).

The way it works is – of course – to create independent clusters which are then imported in Rancher but I am wasting expensive resources (master nodes for etcd, control plane etc) on these providers and also won't be able to use intra-cluster routing.

**Comment by vitobotta** [comment]
Ok but what about latency between nodes with different providers?

**Comment by Privatecoder** [comment]
They don't matter too much as workloads are scheduled on specific nodes (region) which have their own DNS resolving directly to them.

As each node has its own ingress deployed the `external traffic <=> node` latency–  which is the important part in my use case – is not affected and the internal traffic is not latency-sensitive (example: DB as statefulset running on hetzners nodes which are occasionally accessed by the external nodes)
