### ISSUE TITLE
Enable kubernetes v1.20

### ISSUE THREAD

**Issue by quorak** [vitobotta/hetzner-k3s#74]
Is it correct, that we currently cannot deploy kubernetes versions before v1.21 because the github api is limited

![image](https://user-images.githubusercontent.com/68172/161420009-adfdb597-9cdb-42e4-8a9e-f6019f19ed52.png)

https://github.com/vitobotta/hetzner-k3s/blob/fcab29db7bf3817457a57561cc32b5aafc127ec8/lib/hetzner/k3s/cli.rb#L195

Would be great to make this more flexible, if there are no other constraints.

**Comment by janosmiko** [comment]
It's possible to fetch the next page of GitHub API using the `&page=2` query string.

Also if you fetch the headers from GitHub the Location header contains both the next and the last page of the current list:
```
curl -IkL "https://api.github.com/repos/k3s-io/k3s/tags?per_page=100&page=1"
HTTP/2 200
server: GitHub.com
date: Mon, 04 Apr 2022 11:03:46 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept, Accept-Encoding, Accept, X-Requested-With
etag: W/"4291a0005fc1ab37fe4893ac4a27ad9d8e3e935870c828371f38c40572df034e"
last-modified: Mon, 04 Apr 2022 09:53:33 GMT
x-github-media-type: github.v3; format=json
link: <https://api.github.com/repositories/135516270/tags?per_page=100&page=2>; rel="next", <https://api.github.com/repositories/135516270/tags?per_page=100&page=5>; rel="last"
```

Sadly I'm not good enough in Ruby to implement the solution.

**Comment by vitobotta** [comment]
Done in v0.5.8.
