### ISSUE TITLE
Add option to put api server also behind allowed netowkrs

### ISSUE THREAD

**Issue by quorak** [vitobotta/hetzner-k3s#76]
In order to add a little security for the api servers, maybe we can automate to create firewall rules to only allow specified networks. Just as we doo for the `ssh_allowed_networks`

```
api_allowed_networks:
  - 0.0.0.0/32
```

**Comment by vitobotta** [comment]
Hi, sorry for the delay but I only now have had time to work a bit on the project. Done in 0.5.9. Let me know if you run into issues. Closing for now since it's implemented.
