### ISSUE TITLE
"wireguard-native" available as flannel-backend option?

### ISSUE THREAD

**Issue by Privatecoder** [vitobotta/hetzner-k3s#79]
Hi @vitobotta ,

I saw the [changelog](https://github.com/k3s-io/k3s/releases/tag/v1.23.6%2Bk3s1) of v1.23.6+k3s1 which includes [wireguard-native](https://github.com/k3s-io/k3s/pull/5391) as flannel backend.

I haven't tried setting up a new cluster using your tool but should that work oob?

Best
Max

**Comment by Privatecoder** [comment]
btw: Please add to the docs that one needs to install wireguard on each worker-/master-node when adding wireguard to an existing cluster ;)

**Comment by vitobotta** [comment]
> btw: Please add to the docs that one needs to install wireguard on each worker-/master-node when adding wireguard to an existing cluster ;)

Actually if you enable encryption wireguard is installed automatically by default https://github.com/vitobotta/hetzner-k3s/blob/783c6af112b7e959b53c5decc33606d86e60e795/lib/hetzner/infra/server.rb#L63

**Comment by Privatecoder** [comment]
but this is only true for new clusters. if there is an existing cluster and one enables encryption wireguard will only be installed on newly added nodes...

**Comment by vitobotta** [comment]
True, you're right

**Comment by Privatecoder** [comment]
Hi @vitobotta,

as it is not unlikely that the `wireguard` legacy option had its stake in the unreliable DNS-responses (_"It kinda sounds like the legacy wireguard setup was dropping some portion of udp DNS traffic."_ [here](https://github.com/k3s-io/k3s/issues/5849#issuecomment-1188508636)) would you mind extending the available options to include `wireguard-native`?

From my understanding we could add an additional variable here

`flannel_wireguard = enable_encryption ? ' --flannel-backend=wireguard ' : ' '` to make it something like

`flannel_wireguard = enable_encryption and wireguard_native and ' --flannel-backend=wireguard-native ' or enable_encryption and ' --flannel-backend=wireguard ' or ' '`

(I am not really into Python..)

This way everything should be backwards-compatible as one would've to set `wireguard_native` to true as well (+ add to the Docs that this is only available in k3s versions >= v1.23.6+k3s1).

What do you think?

**Comment by Privatecoder** [comment]
That is why I created the PR for you :)

**Comment by vitobotta** [comment]
Hi, sorry for the delay but I only now have had time to work a bit on the project. Done in 0.5.9. Let me know if you run into issues. Closing for now since it's implemented.

**Comment by vitobotta** [comment]
Oops... I had forgotten that you made a PR for this, sorry. Anyway I prefer to make this change transparent to the user.
