### ISSUE TITLE
Scale master node up

### ISSUE THREAD

**Issue by flobaader** [vitobotta/hetzner-k3s#81]
Hello @vitobotta,

as far as I can tell, there is currently no way to upscale a Kubernetes master by making a change in the config file. Is there a trick for this?

Best regards and thanks for the awesome tool!
Florian

**Comment by flobaader** [comment]
@vitobotta I did not mean to increas the number of nodes, but instead scale the master nodes from cx11 to cx21 for example.

**Comment by vitobotta** [comment]
Oh sorry, I misunderstood. That's not directly supported by my tool at the moment. You'd have to scale using the Hetzner control panel.
