### ISSUE TITLE
Unable to create-cluster with 0.5.7

### ISSUE THREAD

**Issue by pysen** [vitobotta/hetzner-k3s#86]
With `0.5.6` the servers can be accessed and create-cluster command works as expected while on `0.5.7` using the same configuration file I see this message when running create-cluster on the servers:

```
$ hetzner-k3s create-cluster --config-file control_plane_config.yaml
Placement group kcp already exists, skipping.
Firewall already exists, skipping.
Private network already exists, skipping.
SSH key already exists, skipping.
Server kcp-cpx41-master2 already exists, skipping.
Server kcp-cpx41-master3 already exists, skipping.
Server kcp-cpx41-master1 already exists, skipping.
Waiting for server kcp-cpx41-master2 to be up...
Waiting for server kcp-cpx41-master1 to be up...
Waiting for server kcp-cpx41-master3 to be up...
```

The last 3 lines are looping trying to connect to the nodes, SSH access works as expected to the machines with the same key as in the configuration.

**Comment by Privatecoder** [comment]
@pysen check [this](https://github.com/vitobotta/hetzner-k3s/issues/80)

**Comment by pysen** [comment]
Thanks for the quick feedback, closing the issue now.
