### ISSUE TITLE
Feature request: Create firewall rules with descriptions

### ISSUE THREAD

**Issue by Xalaxis** [vitobotta/hetzner-k3s#9]
Hetzner firewalls (now? I think this was added recently) support a description field per-rule. Please can the automatically added rules have descriptions for human readability :)?

**Comment by vitobotta** [comment]
Sure, will take a look. What kind of description? Like "https" for port 443 and "Kubernetes API server" for 6443? Not sure what else I can say in the descriptions 🙂

**Comment by Xalaxis** [comment]
Yeah, that's basically what I was thinking. ICMP is obviously for ICMP echo (ping), 22 for the SSH etc.

Just thought it would be a nice-to-have 😁

**Comment by vitobotta** [comment]
Ok, will add it 🖖

**Comment by vitobotta** [comment]
Added in 0.3.5. I guess we can close? :)

**Comment by Xalaxis** [comment]
Definitely, thanks again for the tool!

**Comment by vitobotta** [comment]
👍
