### ISSUE TITLE
Is there a way to regenerate local kubeconfig?

### ISSUE THREAD

**Issue by TitanFighter** [vitobotta/hetzner-k3s#92]
Hi Vito.

For some reason my local `kubeconfig` file disappeared.
Initially hetzner-k3s was installed through Docker. I have access to all master and worker servers and I see that master has `/etc/rancher/k3s/k3s.yaml`, but `server` is `https:127.0.0.1:6443` and `cluster`/`user`/`name` all are `default`.

Is there a way to regenerate local kubeconfig?

Thank you.

**Comment by vitobotta** [comment]
Hi, if you rerun the create script it should recreate the kubeconfig file.

**Comment by TitanFighter** [comment]
Thank you - it works!
I was thinking about this way, but just wanted to be sure that this can be safe.
